export interface Saja {
  hanja: string
  sound: string
  meaning: string
  origin: string
}

export const sajaList: Saja[] = [
  { hanja: "一石二鳥", sound: "일석이조", meaning: "돌 하나로 새 두 마리를 잡는다", origin: "한 가지 일로 두 가지 이득을 얻음" },
  { hanja: "七轉八起", sound: "칠전팔기", meaning: "일곱 번 넘어져도 여덟 번 일어난다", origin: "몇 번을 실패해도 굽히지 않고 다시 일어남" },
  { hanja: "登高自卑", sound: "등고자비", meaning: "높은 곳에 오르려면 낮은 곳부터", origin: "무슨 일이든 순서를 밟아야 함" },
  { hanja: "愚公移山", sound: "우공이산", meaning: "우공이 산을 옮긴다", origin: "꾸준히 노력하면 어떤 일이든 이룰 수 있음" },
  { hanja: "切磋琢磨", sound: "절차탁마", meaning: "옥돌을 갈고 닦는다", origin: "학문·덕행을 끊임없이 갈고 닦음" },
  { hanja: "見物生心", sound: "견물생심", meaning: "물건을 보면 욕심이 생긴다", origin: "탐나는 것을 보면 갖고 싶은 마음이 생김" },
  { hanja: "同病相憐", sound: "동병상련", meaning: "같은 병을 앓는 사람끼리 서로 불쌍히 여긴다", origin: "어려운 처지에 있는 사람끼리 서로 동정함" },
  { hanja: "塞翁之馬", sound: "새옹지마", meaning: "변방 노인의 말", origin: "인생의 길흉화복은 예측하기 어려움" },
  { hanja: "臥薪嘗膽", sound: "와신상담", meaning: "섶에 눕고 쓸개를 맛본다", origin: "원수를 갚기 위해 온갖 어려움을 참고 견딤" },
  { hanja: "刻骨難忘", sound: "각골난망", meaning: "뼈에 새겨 잊기 어렵다", origin: "입은 은혜가 깊어 잊을 수 없음" },
  { hanja: "苦盡甘來", sound: "고진감래", meaning: "쓴 것이 다하면 단 것이 온다", origin: "고생 끝에 즐거움이 옴" },
  { hanja: "近墨者黑", sound: "근묵자흑", meaning: "먹을 가까이하면 검어진다", origin: "나쁜 사람과 어울리면 나쁜 영향을 받음" },
  { hanja: "大器晩成", sound: "대기만성", meaning: "큰 그릇은 늦게 이루어진다", origin: "크게 될 사람은 늦게 성공함" },
  { hanja: "同舟共濟", sound: "동주공제", meaning: "같은 배를 타고 함께 건넌다", origin: "어려운 상황에서 서로 협력함" },
  { hanja: "磨斧作針", sound: "마부작침", meaning: "도끼를 갈아 바늘을 만든다", origin: "꾸준한 노력으로 어떤 일이든 이룰 수 있음" },
  { hanja: "百折不屈", sound: "백절불굴", meaning: "백 번 꺾여도 굽히지 않는다", origin: "어떤 어려움에도 굴복하지 않는 강인한 의지" },
  { hanja: "先公後私", sound: "선공후사", meaning: "공적인 일을 먼저, 사적인 일을 나중에", origin: "개인보다 공공의 이익을 우선시함" },
  { hanja: "以心傳心", sound: "이심전심", meaning: "마음에서 마음으로 전한다", origin: "말 없이도 마음이 서로 통함" },
  { hanja: "自業自得", sound: "자업자득", meaning: "자신이 한 일의 결과는 자신이 받는다", origin: "자기가 저지른 일의 결과를 자기가 받음" },
  { hanja: "朝三暮四", sound: "조삼모사", meaning: "아침에 셋, 저녁에 넷", origin: "눈앞의 차이만 알고 결과가 같음을 모름. 간사한 꾀로 남을 속임" },
  { hanja: "靑出於藍", sound: "청출어람", meaning: "푸른색은 쪽에서 나온다", origin: "제자가 스승보다 뛰어남" },
  { hanja: "螳螂拒轍", sound: "당랑거철", meaning: "사마귀가 수레바퀴를 막는다", origin: "자기 분수를 모르고 강한 상대에게 무모하게 덤빔" },
  { hanja: "破竹之勢", sound: "파죽지세", meaning: "대나무를 쪼개는 기세", origin: "막힘없이 나아가는 맹렬한 기세" },
  { hanja: "四面楚歌", sound: "사면초가", meaning: "사방이 적의 노래로 둘러싸이다", origin: "아무도 도와주지 않는 외롭고 고립된 상태" },
  { hanja: "過猶不及", sound: "과유불급", meaning: "지나침은 미치지 못함과 같다", origin: "무엇이든 지나치면 부족함과 마찬가지로 나쁨" },
  { hanja: "水魚之交", sound: "수어지교", meaning: "물과 물고기의 사귐", origin: "매우 친밀하여 떼려야 뗄 수 없는 사이" },
  { hanja: "一日三省", sound: "일일삼성", meaning: "하루에 세 번 자신을 반성한다", origin: "날마다 자기 자신을 깊이 반성함" },
  { hanja: "溫故知新", sound: "온고지신", meaning: "옛것을 익혀 새것을 안다", origin: "과거를 바탕으로 새로운 것을 배우고 깨달음" },
  { hanja: "虎死留皮", sound: "호사유피", meaning: "범은 죽어 가죽을 남긴다", origin: "사람은 죽어 이름을 남겨야 함" },
  { hanja: "十年苦功", sound: "십년고공", meaning: "십 년의 고된 노력", origin: "오랜 세월 동안 꾸준히 노력함" },
  { hanja: "一擧兩得", sound: "일거양득", meaning: "한 가지 일로 두 가지 이득을 얻는다", origin: "한 번의 행동으로 두 가지 성과를 거둠" },
  { hanja: "三人成虎", sound: "삼인성호", meaning: "세 사람이 호랑이를 만들어낸다", origin: "여럿이 거짓말을 하면 사실로 믿게 됨" },
  { hanja: "三顧草廬", sound: "삼고초려", meaning: "초가집을 세 번 찾아간다", origin: "인재를 얻기 위해 참을성 있게 예를 갖추어 청함" },
  { hanja: "馬耳東風", sound: "마이동풍", meaning: "말의 귀에 동풍", origin: "남의 말을 전혀 귀담아듣지 않음" },
  { hanja: "竹馬故友", sound: "죽마고우", meaning: "죽마를 타고 놀던 옛 친구", origin: "어릴 때부터 같이 자란 오랜 친구" },
  { hanja: "指鹿爲馬", sound: "지록위마", meaning: "사슴을 가리켜 말이라 한다", origin: "윗사람을 농락하여 권세를 마음대로 함" },
  { hanja: "狐假虎威", sound: "호가호위", meaning: "여우가 호랑이의 위세를 빌린다", origin: "남의 권세를 빌려 위세를 부림" },
  { hanja: "畵龍點睛", sound: "화룡점정", meaning: "용을 그리고 눈동자를 찍는다", origin: "가장 중요한 부분을 마지막에 완성함" },
  { hanja: "五里霧中", sound: "오리무중", meaning: "5리 안개 속에 있다", origin: "무슨 일인지 갈피를 잡을 수 없는 상태" },
  { hanja: "半信半疑", sound: "반신반의", meaning: "반은 믿고 반은 의심한다", origin: "믿어야 할지 의심해야 할지 모르는 상태" },
  { hanja: "附和雷同", sound: "부화뇌동", meaning: "남의 말에 덮어놓고 동조한다", origin: "자기 주견 없이 남의 의견에 무조건 따름" },
  { hanja: "粉骨碎身", sound: "분골쇄신", meaning: "뼈가 가루가 되고 몸이 부서지다", origin: "있는 힘을 다해 노력함" },
  { hanja: "不恥下問", sound: "불치하문", meaning: "아랫사람에게 묻기를 부끄러워하지 않는다", origin: "모르는 것을 겸손하게 배우는 자세" },
  { hanja: "改過遷善", sound: "개과천선", meaning: "잘못을 고치고 착하게 된다", origin: "지난날의 잘못을 깨닫고 바른 길로 들어섬" },
  { hanja: "牽强附會", sound: "견강부회", meaning: "억지로 끌어다 붙인다", origin: "이치에 맞지 않는 말을 억지로 끌어다 붙임" },
  { hanja: "結草報恩", sound: "결초보은", meaning: "풀을 묶어 은혜를 갚는다", origin: "죽어서도 은혜를 잊지 않고 갚음" },
  { hanja: "輕擧妄動", sound: "경거망동", meaning: "가볍게 움직이고 망령되게 행동한다", origin: "경솔하고 신중하지 못한 행동" },
  { hanja: "孤立無援", sound: "고립무원", meaning: "고립되어 도움이 없다", origin: "혼자 떨어져 아무런 도움을 받지 못하는 상태" },
  { hanja: "管鮑之交", sound: "관포지교", meaning: "관중과 포숙의 사귐", origin: "우정이 매우 돈독한 친구 사이" },
  { hanja: "刮目相對", sound: "괄목상대", meaning: "눈을 비비고 상대를 다시 본다", origin: "남의 학식이나 재주가 놀랍게 발전함" },
  { hanja: "敎學相長", sound: "교학상장", meaning: "가르치고 배우면서 함께 성장한다", origin: "가르치면서 스스로도 배우고 성장함" },
  { hanja: "九死一生", sound: "구사일생", meaning: "아홉 번 죽을 고비에서 겨우 살아남", origin: "여러 번 죽을 고비를 넘기고 겨우 살아남" },
  { hanja: "九牛一毛", sound: "구우일모", meaning: "아홉 마리 소 중 털 하나", origin: "매우 많은 것 중의 아주 작은 것" },
  { hanja: "群鷄一鶴", sound: "군계일학", meaning: "닭 무리 중의 학", origin: "평범한 사람들 중에 뛰어난 인물" },
  { hanja: "勸善懲惡", sound: "권선징악", meaning: "착함을 권하고 악함을 징계한다", origin: "착한 행동을 장려하고 나쁜 행동을 벌함" },
  { hanja: "金科玉條", sound: "금과옥조", meaning: "금이나 옥처럼 귀중한 법칙", origin: "매우 소중하게 여기는 규칙이나 법칙" },
  { hanja: "錦上添花", sound: "금상첨화", meaning: "비단 위에 꽃을 더한다", origin: "좋은 것에 더 좋은 것이 더해짐" },
  { hanja: "起死回生", sound: "기사회생", meaning: "죽어가다가 다시 살아난다", origin: "절망적인 상황에서 다시 살아나거나 회복됨" },
  { hanja: "奇想天外", sound: "기상천외", meaning: "생각이 하늘 밖까지 이른다", origin: "보통 사람은 생각할 수 없을 만큼 기발한 생각" },
  { hanja: "內憂外患", sound: "내우외환", meaning: "안으로는 근심, 밖으로는 걱정", origin: "안팎으로 여러 가지 어려움과 걱정이 겹침" },
  { hanja: "勞心焦思", sound: "노심초사", meaning: "마음을 써서 애를 태운다", origin: "몹시 걱정하고 애를 씀" },
  { hanja: "單刀直入", sound: "단도직입", meaning: "혼자 칼을 들고 바로 쳐들어간다", origin: "서론 없이 바로 요점이나 핵심을 말함" },
  { hanja: "桃園結義", sound: "도원결의", meaning: "복숭아밭에서 의를 맺는다", origin: "유비·관우·장비가 맺은 것처럼 굳은 맹세를 함" },
  { hanja: "同價紅裳", sound: "동가홍상", meaning: "같은 값이면 다홍치마", origin: "같은 조건이라면 더 좋은 것을 선택함" },
  { hanja: "東問西答", sound: "동문서답", meaning: "동쪽을 묻는데 서쪽으로 대답한다", origin: "묻는 말에 전혀 엉뚱한 대답을 함" },
  { hanja: "杜門不出", sound: "두문불출", meaning: "문을 닫고 밖에 나가지 않는다", origin: "집 안에만 틀어박혀 세상과 단절함" },
  { hanja: "莫無可奈", sound: "막무가내", meaning: "어찌할 수 없다", origin: "고집이 세어 도무지 융통성이 없음" },
  { hanja: "亡羊補牢", sound: "망양보뢰", meaning: "양을 잃고 우리를 고친다", origin: "이미 일이 잘못된 뒤에 손써도 소용없음" },
  { hanja: "明鏡止水", sound: "명경지수", meaning: "맑은 거울과 고요한 물", origin: "잡념 없이 맑고 고요한 마음" },
  { hanja: "名實相符", sound: "명실상부", meaning: "이름과 실제가 서로 맞는다", origin: "이름과 실제 내용이 꼭 들어맞음" },
  { hanja: "目不忍見", sound: "목불인견", meaning: "눈 뜨고 볼 수 없다", origin: "차마 눈을 뜨고 볼 수 없을 만큼 딱하거나 끔찍함" },
  { hanja: "武陵桃源", sound: "무릉도원", meaning: "무릉의 복숭아 꽃 피는 곳", origin: "속세를 떠난 아름답고 평화로운 이상향" },
  { hanja: "博學多識", sound: "박학다식", meaning: "넓게 배우고 많이 안다", origin: "학문이 넓고 지식이 풍부함" },
  { hanja: "反哺之孝", sound: "반포지효", meaning: "까마귀가 자라서 어미에게 먹이를 물어다 준다", origin: "자식이 부모의 은혜를 갚는 효도" },
  { hanja: "百年偕老", sound: "백년해로", meaning: "백 년을 함께 늙는다", origin: "부부가 평생 사이 좋게 함께 늙어감" },
  { hanja: "百聞不如一見", sound: "백문불여일견", meaning: "백 번 듣는 것이 한 번 보는 것만 못하다", origin: "직접 경험하는 것이 가장 확실함" },
  { hanja: "本末顚倒", sound: "본말전도", meaning: "근본과 끝이 뒤바뀐다", origin: "중요한 것과 중요하지 않은 것이 뒤바뀜" },
  { hanja: "父傳子傳", sound: "부전자전", meaning: "아버지에게서 아들로 전해진다", origin: "대를 이어 전해져 내려옴" },
  { hanja: "事必歸正", sound: "사필귀정", meaning: "모든 일은 반드시 바른 길로 돌아온다", origin: "잘못된 일도 결국은 바르게 됨" },
  { hanja: "沙上樓閣", sound: "사상누각", meaning: "모래 위의 누각", origin: "기초가 튼튼하지 못해 오래가지 못할 일" },
  { hanja: "山戰水戰", sound: "산전수전", meaning: "산에서도 물에서도 싸웠다", origin: "세상의 온갖 고난과 어려움을 다 겪음" },
  { hanja: "殺身成仁", sound: "살신성인", meaning: "몸을 죽여 인을 이룬다", origin: "자신을 희생하여 옳은 일을 이룸" },
  { hanja: "相扶相助", sound: "상부상조", meaning: "서로 돕고 서로 도움을 받는다", origin: "서로서로 돕는 것" },
  { hanja: "先見之明", sound: "선견지명", meaning: "먼저 앞을 내다보는 밝은 지혜", origin: "앞일을 미리 내다보는 총명함" },
  { hanja: "雪上加霜", sound: "설상가상", meaning: "눈 위에 서리까지", origin: "어려운 일이 거듭 겹침" },
  { hanja: "小貪大失", sound: "소탐대실", meaning: "작은 것을 탐내다 큰 것을 잃는다", origin: "작은 이익을 탐하다가 큰 손해를 입음" },
  { hanja: "袖手傍觀", sound: "수수방관", meaning: "소매에 손을 넣고 곁에서 구경만 한다", origin: "관계없다는 듯이 그냥 보고만 있음" },
  { hanja: "時機尙早", sound: "시기상조", meaning: "때가 아직 이르다", origin: "어떤 일을 하기에 아직 때가 되지 않음" },
  { hanja: "信賞必罰", sound: "신상필벌", meaning: "상은 반드시 믿게 주고 벌은 반드시 준다", origin: "공이 있는 자에게는 반드시 상을, 죄가 있는 자에게는 반드시 벌을 줌" },
  { hanja: "心機一轉", sound: "심기일전", meaning: "마음의 기틀을 한 번 바꾼다", origin: "새로운 마음으로 다시 시작함" },
  { hanja: "我田引水", sound: "아전인수", meaning: "내 논에 물을 끌어온다", origin: "자기에게만 유리하게 생각하거나 행동함" },
  { hanja: "眼下無人", sound: "안하무인", meaning: "눈 아래 사람이 없다", origin: "방자하고 교만하여 남을 업신여김" },
  { hanja: "弱肉强食", sound: "약육강식", meaning: "약한 자는 강한 자의 먹이가 된다", origin: "강한 자가 약한 자를 지배하는 냉혹한 현실" },
  { hanja: "羊頭狗肉", sound: "양두구육", meaning: "양 머리를 걸어 놓고 개고기를 판다", origin: "겉으로 내세우는 것과 실제가 다름" },
  { hanja: "漁父之利", sound: "어부지리", meaning: "어부가 이익을 취한다", origin: "두 사람이 싸우는 틈에 제3자가 이득을 봄" },
  { hanja: "易地思之", sound: "역지사지", meaning: "처지를 바꿔 생각한다", origin: "상대방의 입장에서 생각해 봄" },
  { hanja: "緣木求魚", sound: "연목구어", meaning: "나무에 올라 물고기를 구한다", origin: "불가능한 일을 하려고 함" },
  { hanja: "寤寐不忘", sound: "오매불망", meaning: "자나 깨나 잊지 못한다", origin: "항상 그리워하고 잊지 못함" },
  { hanja: "烏合之卒", sound: "오합지졸", meaning: "까마귀 떼처럼 모인 병사", origin: "규율도 통솔력도 없이 모인 무리" },
  { hanja: "外柔內剛", sound: "외유내강", meaning: "겉은 부드럽고 속은 강하다", origin: "겉보기에는 부드럽지만 속은 강인함" },
  { hanja: "龍頭蛇尾", sound: "용두사미", meaning: "용의 머리에 뱀의 꼬리", origin: "시작은 거창하지만 끝이 초라함" },
  { hanja: "有備無患", sound: "유비무환", meaning: "준비가 있으면 걱정이 없다", origin: "미리 준비하면 걱정할 것이 없음" },
  { hanja: "類類相從", sound: "유유상종", meaning: "같은 무리끼리 서로 따른다", origin: "비슷한 사람들끼리 서로 어울림" },
  { hanja: "日就月將", sound: "일취월장", meaning: "날로 달로 나아가고 발전한다", origin: "학업이나 실력이 빠르게 향상됨" },
  { hanja: "臨機應變", sound: "임기응변", meaning: "그때그때 기회에 맞게 변한다", origin: "상황에 따라 적절하게 대처함" },
  { hanja: "自家撞着", sound: "자가당착", meaning: "자기 집에서 자기와 부딪힌다", origin: "자기의 말이나 행동이 앞뒤가 맞지 않음" },
  { hanja: "自暴自棄", sound: "자포자기", meaning: "스스로 사납게 굴고 스스로 버린다", origin: "절망하여 스스로를 포기함" },
  { hanja: "轉禍爲福", sound: "전화위복", meaning: "화가 바뀌어 복이 된다", origin: "재앙이 바뀌어 오히려 좋은 일이 됨" },
  { hanja: "漸入佳境", sound: "점입가경", meaning: "점점 좋은 경지로 들어간다", origin: "일이 갈수록 더 재미있거나 흥미로운 상태" },
  { hanja: "走馬看山", sound: "주마간산", meaning: "말을 달리며 산을 본다", origin: "바빠서 자세히 살피지 않고 대충 훑어봄" },
  { hanja: "進退兩難", sound: "진퇴양난", meaning: "나아가기도 물러나기도 어렵다", origin: "이러지도 저러지도 못하는 곤란한 처지" },
  { hanja: "天高馬肥", sound: "천고마비", meaning: "하늘은 높고 말은 살찐다", origin: "가을철의 맑고 풍요로운 계절" },
  { hanja: "千辛萬苦", sound: "천신만고", meaning: "천 가지 매운 것과 만 가지 쓴 것", origin: "온갖 어렵고 힘든 고생을 다 겪음" },
  { hanja: "千載一遇", sound: "천재일우", meaning: "천 년에 한 번 만난다", origin: "좀처럼 얻기 어려운 좋은 기회" },
  { hanja: "初志一貫", sound: "초지일관", meaning: "처음 뜻을 끝까지 밀고 나간다", origin: "처음에 세운 뜻을 끝까지 꾸준히 지킴" },
  { hanja: "七步之才", sound: "칠보지재", meaning: "일곱 걸음 안에 시를 짓는 재주", origin: "매우 뛰어난 문학적 재능" },
  { hanja: "他山之石", sound: "타산지석", meaning: "다른 산의 돌", origin: "다른 사람의 사소한 언행도 자신의 수양에 도움이 됨" },
  { hanja: "泰然自若", sound: "태연자약", meaning: "태연하고 스스로 여유롭다", origin: "어떤 상황에서도 침착하고 여유 있게 행동함" },
  { hanja: "表裏不同", sound: "표리부동", meaning: "겉과 속이 같지 않다", origin: "말과 행동, 또는 겉과 속이 다름" },
  { hanja: "風前燈火", sound: "풍전등화", meaning: "바람 앞의 등불", origin: "매우 위태롭고 아슬아슬한 상황" },
  { hanja: "汗牛充棟", sound: "한우충동", meaning: "소가 땀을 흘리고 대들보까지 차다", origin: "책이 매우 많음" },
  { hanja: "虛心坦懷", sound: "허심탄회", meaning: "마음을 비우고 가슴을 터놓는다", origin: "거리낌 없이 솔직하게 터놓고 이야기함" },
  { hanja: "螢雪之功", sound: "형설지공", meaning: "반딧불과 눈빛으로 이룬 공부", origin: "어려운 환경 속에서도 꿋꿋하게 공부한 노력" },
  { hanja: "虎虎益壯", sound: "호호익장", meaning: "갈수록 더욱 씩씩하고 강해진다", origin: "늙을수록 더욱 기운차고 강해짐" },
  { hanja: "弘益人間", sound: "홍익인간", meaning: "널리 인간을 이롭게 한다", origin: "단군의 건국 이념, 인류 전체의 이익을 위함" },
  { hanja: "和而不同", sound: "화이부동", meaning: "화합하되 부화뇌동하지 않는다", origin: "남과 사이좋게 지내되 자기 소신을 지킴" },
  { hanja: "刻舟求劍", sound: "각주구검", meaning: "배에 칼을 새겨 칼을 찾는다", origin: "상황 변화를 모르고 융통성 없이 구식 방법만 고집함" },
  { hanja: "甘言利說", sound: "감언이설", meaning: "달콤한 말과 이로운 말로 꾀인다", origin: "달콤한 말로 상대방을 유혹하거나 속임" },
  { hanja: "苛斂誅求", sound: "가렴주구", meaning: "가혹하게 세금을 거두고 재물을 빼앗는다", origin: "지배층이 백성으로부터 가혹하게 재물을 착취함" },
  { hanja: "曲學阿世", sound: "곡학아세", meaning: "학문을 굽혀 세속에 아첨한다", origin: "진리를 굽히고 세상 사람들에게 아첨함" },
  { hanja: "姑息之計", sound: "고식지계", meaning: "고식적인 계책", origin: "당장의 편안함만을 위한 임시방편" },
  { hanja: "孤掌難鳴", sound: "고장난명", meaning: "손바닥 하나로는 소리가 나지 않는다", origin: "혼자서는 일을 이루기 어려움" },
  { hanja: "誇大妄想", sound: "과대망상", meaning: "과장하여 망령된 생각을 한다", origin: "자신을 지나치게 크게 여기는 헛된 생각" },
  { hanja: "矯角殺牛", sound: "교각살우", meaning: "뿔을 바로잡으려다 소를 죽인다", origin: "작은 흠을 고치려다 오히려 일을 그르침" },
  { hanja: "群盲評象", sound: "군맹평상", meaning: "장님 여럿이 코끼리를 평한다", origin: "좁은 시각으로 사물의 일부만 보고 전체를 판단함" },
  { hanja: "近朱者赤", sound: "근주자적", meaning: "붉은색을 가까이하면 붉어진다", origin: "좋은 사람과 어울리면 좋은 영향을 받음" },
  { hanja: "落花流水", sound: "낙화유수", meaning: "떨어진 꽃과 흐르는 물", origin: "남녀 사이가 서로 그리워하며 정이 듦" },
  { hanja: "累卵之危", sound: "누란지위", meaning: "쌓아 놓은 달걀처럼 위태롭다", origin: "매우 위험하고 불안한 상태" },
  { hanja: "同苦同樂", sound: "동고동락", meaning: "괴로움도 즐거움도 함께한다", origin: "어려울 때나 즐거울 때나 항상 함께함" },
  { hanja: "得意忘形", sound: "득의망형", meaning: "뜻을 이루어 형태를 잊는다", origin: "너무 기쁘거나 흥분하여 자신을 잊음" },
  { hanja: "萬事亨通", sound: "만사형통", meaning: "모든 일이 다 잘 통한다", origin: "모든 일이 뜻대로 잘 되어 나감" },
  { hanja: "門前成市", sound: "문전성시", meaning: "문 앞이 시장처럼 된다", origin: "찾아오는 사람이 많아 대단히 번성함" },
  { hanja: "無我之境", sound: "무아지경", meaning: "자아가 없는 경지", origin: "어떤 일에 완전히 빠져 자신을 잊은 상태" },
  { hanja: "美風良俗", sound: "미풍양속", meaning: "아름다운 바람과 좋은 풍속", origin: "아름답고 좋은 사회 풍속이나 관습" },
  { hanja: "問一知十", sound: "문일지십", meaning: "하나를 물으면 열을 안다", origin: "매우 영리하고 총명함" },
  { hanja: "拍掌大笑", sound: "박장대소", meaning: "손뼉을 치며 크게 웃는다", origin: "매우 재미있어서 손뼉을 치며 크게 웃음" },
  { hanja: "拔本塞源", sound: "발본색원", meaning: "뿌리를 뽑고 근원을 막는다", origin: "폐단의 근본 원인을 철저히 없앰" },
  { hanja: "傍若無人", sound: "방약무인", meaning: "곁에 사람이 없는 것처럼 행동한다", origin: "제멋대로 행동하며 다른 사람을 전혀 의식하지 않음" },
  { hanja: "白骨難忘", sound: "백골난망", meaning: "백골이 되어도 잊기 어렵다", origin: "죽어서도 잊을 수 없는 큰 은혜" },
  { hanja: "伯牙絶絃", sound: "백아절현", meaning: "백아가 거문고 줄을 끊는다", origin: "자기를 진정으로 알아주는 사람의 죽음을 슬퍼함" },
  { hanja: "非夢似夢", sound: "비몽사몽", meaning: "꿈도 아니고 꿈같다", origin: "잠이 완전히 들지 않은 어렴풋한 상태" },
  { hanja: "非一非再", sound: "비일비재", meaning: "한두 번이 아니다", origin: "같은 일이 매우 자주 있음" },
  { hanja: "貧賤之交", sound: "빈천지교", meaning: "가난하고 천할 때 사귄 친구", origin: "어렵고 힘든 시절을 함께한 소중한 친구" },
  { hanja: "士氣衝天", sound: "사기충천", meaning: "사기가 하늘을 찌른다", origin: "의욕과 기세가 매우 높고 강함" },
  { hanja: "森羅萬象", sound: "삼라만상", meaning: "숲처럼 늘어선 만 가지 모습", origin: "우주 사이에 존재하는 온갖 사물과 현상" },
  { hanja: "生死苦樂", sound: "생사고락", meaning: "삶과 죽음, 괴로움과 즐거움", origin: "인생에서 겪게 되는 온갖 일들" },
  { hanja: "以卵擊石", sound: "이란격석", meaning: "달걀로 돌을 친다", origin: "약한 것이 강한 것에 무모하게 대항함" },
  { hanja: "一刀兩斷", sound: "일도양단", meaning: "한 칼에 두 동강을 낸다", origin: "과감하고 명쾌하게 결단함" },
  { hanja: "一波萬波", sound: "일파만파", meaning: "한 파도가 만 파도를 일으킨다", origin: "하나의 일이 그 영향이 퍼져 여러 일을 일으킴" },
  { hanja: "自强不息", sound: "자강불식", meaning: "스스로 강해지기를 멈추지 않는다", origin: "스스로 힘써 쉬지 않고 부지런히 노력함" },
  { hanja: "自初至終", sound: "자초지종", meaning: "처음부터 끝까지", origin: "일이 시작된 처음부터 끝날 때까지의 전 과정" },
  { hanja: "積小成大", sound: "적소성대", meaning: "작은 것이 쌓여 큰 것이 된다", origin: "작은 노력이 쌓이면 큰 성과를 이룸" },
  { hanja: "井底之蛙", sound: "정저지와", meaning: "우물 안의 개구리", origin: "식견이 좁아 세상 형편을 모르는 사람" },
  { hanja: "朝令暮改", sound: "조령모개", meaning: "아침에 명령하고 저녁에 고친다", origin: "법령이나 명령이 자주 바뀜" },
  { hanja: "種豆得豆", sound: "종두득두", meaning: "콩을 심으면 콩을 얻는다", origin: "원인에 따라 결과가 따름, 인과응보" },
  { hanja: "竹林七賢", sound: "죽림칠현", meaning: "대나무 숲의 일곱 현인", origin: "세속을 피해 자연 속에서 유유자적하는 무리" },
  { hanja: "知己之友", sound: "지기지우", meaning: "자기를 알아주는 친구", origin: "서로를 깊이 이해하고 알아주는 친한 친구" },
  { hanja: "知彼知己", sound: "지피지기", meaning: "적을 알고 나를 안다", origin: "상대방과 자신의 형편을 잘 알면 백전백승함" },
  { hanja: "此日彼日", sound: "차일피일", meaning: "이 날 저 날 미룬다", origin: "해야 할 일을 이리저리 자꾸 미룸" },
  { hanja: "滄海一粟", sound: "창해일속", meaning: "넓은 바다의 좁쌀 한 알", origin: "매우 크고 넓은 것에 비해 매우 작고 미미한 것" },
  { hanja: "天壤之差", sound: "천양지차", meaning: "하늘과 땅의 차이", origin: "두 가지 사물이나 상태의 차이가 매우 큼" },
  { hanja: "天下泰平", sound: "천하태평", meaning: "천하가 매우 평화롭다", origin: "세상이 아주 평화롭거나, 아무 걱정 없이 태평함" },
  { hanja: "徹頭徹尾", sound: "철두철미", meaning: "머리부터 꼬리까지 철저하다", origin: "처음부터 끝까지 철저하고 빈틈없이 함" },
  { hanja: "靑天霹靂", sound: "청천벽력", meaning: "맑은 하늘의 벼락", origin: "뜻밖에 일어난 큰 충격이나 사건" },
  { hanja: "草綠同色", sound: "초록동색", meaning: "풀빛과 녹색은 같은 색이다", origin: "같은 무리끼리 어울림" },
  { hanja: "秋風落葉", sound: "추풍낙엽", meaning: "가을바람에 떨어지는 낙엽", origin: "세력이 약해져 어지럽게 흩어짐" },
  { hanja: "七縱七擒", sound: "칠종칠금", meaning: "일곱 번 풀어주고 일곱 번 잡는다", origin: "마음대로 다루거나 완전히 제압함" },
  { hanja: "快刀亂麻", sound: "쾌도난마", meaning: "잘 드는 칼로 엉킨 실을 끊는다", origin: "복잡하게 얽힌 문제를 명쾌하게 해결함" },
  { hanja: "波瀾萬丈", sound: "파란만장", meaning: "물결이 만 길이나 된다", origin: "사람의 생애나 사물의 변화가 매우 심하고 굴곡이 많음" },
  { hanja: "八方美人", sound: "팔방미인", meaning: "팔방이 다 미인이다", origin: "여러 방면에 능통한 사람, 또는 누구에게나 잘 보이는 사람" },
  { hanja: "抱腹絶倒", sound: "포복절도", meaning: "배를 안고 넘어질 만큼 웃는다", origin: "너무 우스워서 배를 잡고 쓰러질 정도로 웃음" },
  { hanja: "匹夫之勇", sound: "필부지용", meaning: "평범한 남자의 용기", origin: "혈기만 믿고 함부로 날뛰는 무모한 용기" },
  { hanja: "學而時習", sound: "학이시습", meaning: "배우고 때로 익힌다", origin: "배운 것을 꾸준히 복습하고 익힘" },
  { hanja: "咸興差使", sound: "함흥차사", meaning: "함흥으로 보낸 차사", origin: "심부름을 가서 소식이 없거나 돌아오지 않음" },
  { hanja: "行雲流水", sound: "행운유수", meaning: "흘러가는 구름과 흐르는 물", origin: "어떤 일에도 막힘없이 자연스럽게 흘러감" },
  { hanja: "虛虛實實", sound: "허허실실", meaning: "허와 실을 섞어서 쓴다", origin: "거짓과 참을 뒤섞어 상대를 교란하는 전술" },
  { hanja: "賢母良妻", sound: "현모양처", meaning: "어진 어머니이자 훌륭한 아내", origin: "자녀 교육에 현명하고 남편을 잘 내조하는 여성" },
  { hanja: "浩然之氣", sound: "호연지기", meaning: "하늘과 땅 사이에 넘치는 넓고 큰 기운", origin: "공명정대하여 부끄러움 없는 도덕적 용기" },
  { hanja: "好事多魔", sound: "호사다마", meaning: "좋은 일에는 마귀가 많다", origin: "좋은 일에는 방해가 많이 따름" },
  { hanja: "禍福無門", sound: "화복무문", meaning: "화와 복에는 문이 없다", origin: "화와 복은 일정한 곳에서 오는 것이 아니라 자기가 만드는 것" },
  { hanja: "換骨奪胎", sound: "환골탈태", meaning: "뼈를 바꾸고 태를 빼앗는다", origin: "면목을 완전히 바꿀 만큼 발전함" },
  { hanja: "興盡悲來", sound: "흥진비래", meaning: "흥이 다하면 슬픔이 온다", origin: "즐거움이 다하면 슬픔이 찾아옴, 인생의 무상함" },
]
