export interface Vocab {
  word: string
  pron: string   // 한국사전식 발음기호 (강세 모음 위에 ´)
  meaning: string
  pos: string
}

export const vocabList: Vocab[] = [
  { word: "abandon",       pron: "[əbǽndən]",        meaning: "버리다, 포기하다",           pos: "v" },
  { word: "abbreviate",    pron: "[əbríːvieɪt]",     meaning: "줄이다, 약자로 쓰다",        pos: "v" },
  { word: "abolish",       pron: "[əbɒ́lɪʃ]",         meaning: "폐지하다",                  pos: "v" },
  { word: "absorb",        pron: "[əbsɔ́ːrb]",         meaning: "흡수하다",                  pos: "v" },
  { word: "abstract",      pron: "[ǽbstrækt]",        meaning: "추상적인; 요약",             pos: "adj/n" },
  { word: "accelerate",    pron: "[əkséləreɪt]",      meaning: "가속하다",                  pos: "v" },
  { word: "accomplish",    pron: "[əkɒ́mplɪʃ]",        meaning: "성취하다",                  pos: "v" },
  { word: "accurate",      pron: "[ǽkjərət]",         meaning: "정확한",                   pos: "adj" },
  { word: "acknowledge",   pron: "[əknɒ́lɪdʒ]",        meaning: "인정하다",                  pos: "v" },
  { word: "adapt",         pron: "[ədǽpt]",           meaning: "적응하다, 개조하다",          pos: "v" },
  { word: "adequate",      pron: "[ǽdɪkwɪt]",         meaning: "적절한, 충분한",             pos: "adj" },
  { word: "adhere",        pron: "[ədhɪ́ər]",          meaning: "고수하다, 부착하다",          pos: "v" },
  { word: "adjacent",      pron: "[ədʒéɪsənt]",       meaning: "인접한",                   pos: "adj" },
  { word: "advocate",      pron: "[ǽdvəkeɪt]",        meaning: "옹호하다; 지지자",           pos: "v/n" },
  { word: "aesthetic",     pron: "[esθétɪk]",         meaning: "심미적인, 미학의",           pos: "adj" },
  { word: "alleviate",     pron: "[əlíːvieɪt]",       meaning: "완화하다",                  pos: "v" },
  { word: "allocate",      pron: "[ǽləkeɪt]",         meaning: "할당하다",                  pos: "v" },
  { word: "alter",         pron: "[ɔ́ːltər]",          meaning: "바꾸다, 변경하다",           pos: "v" },
  { word: "ambiguous",     pron: "[æmbɪ́ɡjuəs]",       meaning: "모호한",                   pos: "adj" },
  { word: "amplify",       pron: "[ǽmplɪfaɪ]",        meaning: "증폭하다, 확대하다",          pos: "v" },
  { word: "analyze",       pron: "[ǽnəlaɪz]",         meaning: "분석하다",                  pos: "v" },
  { word: "anticipate",    pron: "[æntɪ́sɪpeɪt]",      meaning: "예상하다",                  pos: "v" },
  { word: "apparent",      pron: "[əpǽrənt]",         meaning: "명백한, 외견상의",           pos: "adj" },
  { word: "apply",         pron: "[əpláɪ]",           meaning: "적용하다, 신청하다",          pos: "v" },
  { word: "approximate",   pron: "[əprɒ́ksɪmɪt]",      meaning: "대략의; 근접하다",           pos: "adj/v" },
  { word: "arbitrary",     pron: "[ɑ́ːrbɪtreri]",      meaning: "임의적인, 독단적인",          pos: "adj" },
  { word: "assert",        pron: "[əsɜ́ːrt]",          meaning: "주장하다",                  pos: "v" },
  { word: "assess",        pron: "[əsés]",            meaning: "평가하다",                  pos: "v" },
  { word: "assign",        pron: "[əsáɪn]",           meaning: "배정하다, 할당하다",          pos: "v" },
  { word: "assume",        pron: "[əsúːm]",           meaning: "가정하다, 추정하다",          pos: "v" },
  { word: "attain",        pron: "[ətéɪn]",           meaning: "달성하다",                  pos: "v" },
  { word: "attribute",     pron: "[ǽtrɪbjuːt]",       meaning: "~의 탓으로 돌리다; 속성",    pos: "v/n" },
  { word: "authentic",     pron: "[ɔːθéntɪk]",        meaning: "진짜의, 진품의",             pos: "adj" },
  { word: "autonomous",    pron: "[ɔːtɒ́nəməs]",       meaning: "자율적인",                  pos: "adj" },
  { word: "benefit",       pron: "[bénɪfɪt]",         meaning: "이익, 혜택; 이롭다",         pos: "n/v" },
  { word: "bias",          pron: "[báɪəs]",           meaning: "편견, 선입견",              pos: "n" },
  { word: "brief",         pron: "[briːf]",            meaning: "간략한; 요약하다",           pos: "adj/v" },
  { word: "broad",         pron: "[brɔːd]",            meaning: "넓은, 광범위한",             pos: "adj" },
  { word: "capable",       pron: "[kéɪpəbəl]",        meaning: "능력 있는, ~할 수 있는",     pos: "adj" },
  { word: "category",      pron: "[kǽtɪɡɔːri]",       meaning: "범주, 종류",                pos: "n" },
  { word: "cease",         pron: "[siːs]",             meaning: "멈추다, 중단하다",           pos: "v" },
  { word: "challenge",     pron: "[tʃǽlɪndʒ]",        meaning: "도전; 도전하다",             pos: "n/v" },
  { word: "chronic",       pron: "[krɒ́nɪk]",          meaning: "만성적인",                  pos: "adj" },
  { word: "clarify",       pron: "[klǽrɪfaɪ]",        meaning: "명확하게 하다",              pos: "v" },
  { word: "classify",      pron: "[klǽsɪfaɪ]",        meaning: "분류하다",                  pos: "v" },
  { word: "coherent",      pron: "[koʊhɪ́ərənt]",      meaning: "일관성 있는, 논리적인",       pos: "adj" },
  { word: "collaborate",   pron: "[kəlǽbəreɪt]",      meaning: "협력하다",                  pos: "v" },
  { word: "commit",        pron: "[kəmɪ́t]",           meaning: "저지르다, 헌신하다",          pos: "v" },
  { word: "compensate",    pron: "[kɒ́mpənseɪt]",      meaning: "보상하다",                  pos: "v" },
  { word: "complex",       pron: "[kɒ́mpleks]",        meaning: "복잡한; 복합체",             pos: "adj/n" },
  { word: "comply",        pron: "[kəmpláɪ]",         meaning: "따르다, 준수하다",           pos: "v" },
  { word: "comprise",      pron: "[kəmpráɪz]",        meaning: "구성하다, 포함하다",          pos: "v" },
  { word: "conceive",      pron: "[kənsíːv]",         meaning: "생각하다, 구상하다",          pos: "v" },
  { word: "conclude",      pron: "[kənklúːd]",        meaning: "결론 짓다, 끝내다",          pos: "v" },
  { word: "conflict",      pron: "[kɒ́nflɪkt]",        meaning: "갈등, 충돌; 충돌하다",       pos: "n/v" },
  { word: "conform",       pron: "[kənfɔ́ːrm]",        meaning: "따르다, 순응하다",           pos: "v" },
  { word: "consequence",   pron: "[kɒ́nsɪkwəns]",      meaning: "결과, 영향",                pos: "n" },
  { word: "constant",      pron: "[kɒ́nstənt]",        meaning: "지속적인, 일정한",           pos: "adj" },
  { word: "constitute",    pron: "[kɒ́nstɪtjuːt]",     meaning: "구성하다, ~에 해당하다",     pos: "v" },
  { word: "constraint",    pron: "[kənstréɪnt]",       meaning: "제약, 제한",                pos: "n" },
  { word: "context",       pron: "[kɒ́ntekst]",        meaning: "맥락, 문맥",                pos: "n" },
  { word: "contribute",    pron: "[kəntrɪ́bjuːt]",     meaning: "기여하다, 공헌하다",          pos: "v" },
  { word: "controversial", pron: "[ˌkɒntrəvɜːrʃə́l]",  meaning: "논란이 되는",               pos: "adj" },
  { word: "convey",        pron: "[kənvéɪ]",          meaning: "전달하다, 운반하다",          pos: "v" },
  { word: "cooperate",     pron: "[koʊɒ́pəreɪt]",      meaning: "협력하다",                  pos: "v" },
  { word: "coordinate",    pron: "[koʊɔ́ːrdɪneɪt]",    meaning: "조율하다, 조정하다",          pos: "v" },
  { word: "correlate",     pron: "[kɒ́rəleɪt]",        meaning: "상관관계가 있다",             pos: "v" },
  { word: "crucial",       pron: "[krúːʃəl]",         meaning: "결정적인, 중요한",           pos: "adj" },
  { word: "deduce",        pron: "[dɪdjúːs]",         meaning: "추론하다, 연역하다",          pos: "v" },
  { word: "define",        pron: "[dɪfáɪn]",          meaning: "정의하다",                  pos: "v" },
  { word: "demonstrate",   pron: "[démənstreɪt]",      meaning: "증명하다, 시연하다",          pos: "v" },
  { word: "derive",        pron: "[dɪráɪv]",          meaning: "이끌어내다, 유래하다",        pos: "v" },
  { word: "despite",       pron: "[dɪspáɪt]",         meaning: "~에도 불구하고",             pos: "prep" },
  { word: "detect",        pron: "[dɪtékt]",          meaning: "발견하다, 감지하다",          pos: "v" },
  { word: "determine",     pron: "[dɪtɜːrmɪ́n]",       meaning: "결정하다, 파악하다",          pos: "v" },
  { word: "diminish",      pron: "[dɪmɪ́nɪʃ]",         meaning: "줄이다, 약화시키다",          pos: "v" },
  { word: "diverse",       pron: "[daɪvɜ́ːrs]",        meaning: "다양한",                   pos: "adj" },
  { word: "dominant",      pron: "[dɒ́mɪnənt]",        meaning: "지배적인, 우세한",           pos: "adj" },
  { word: "dramatic",      pron: "[drəmǽtɪk]",        meaning: "극적인, 급격한",             pos: "adj" },
  { word: "elaborate",     pron: "[ɪlǽbərɪt]",        meaning: "정교한; 자세히 설명하다",     pos: "adj/v" },
  { word: "eliminate",     pron: "[ɪlɪ́mɪneɪt]",       meaning: "제거하다",                  pos: "v" },
  { word: "emerge",        pron: "[ɪmɜ́ːrdʒ]",         meaning: "나타나다, 부상하다",          pos: "v" },
  { word: "emphasis",      pron: "[émfəsɪs]",         meaning: "강조",                     pos: "n" },
  { word: "enable",        pron: "[ɪnéɪbəl]",         meaning: "가능하게 하다",              pos: "v" },
  { word: "encounter",     pron: "[ɪnkáʊntər]",       meaning: "마주치다; 만남",             pos: "v/n" },
  { word: "enhance",       pron: "[ɪnhǽns]",          meaning: "향상시키다",                pos: "v" },
  { word: "enormous",      pron: "[ɪnɔ́ːrməs]",        meaning: "거대한, 막대한",             pos: "adj" },
  { word: "essential",     pron: "[ɪsénʃəl]",         meaning: "필수적인",                  pos: "adj" },
  { word: "establish",     pron: "[ɪstǽblɪʃ]",        meaning: "설립하다, 확립하다",          pos: "v" },
  { word: "evaluate",      pron: "[ɪvǽljueɪt]",       meaning: "평가하다",                  pos: "v" },
  { word: "evolve",        pron: "[ɪvɒ́lv]",           meaning: "진화하다, 발전하다",          pos: "v" },
  { word: "exclude",       pron: "[ɪksklúːd]",        meaning: "제외하다",                  pos: "v" },
  { word: "exhibit",       pron: "[ɪɡzɪ́bɪt]",         meaning: "전시하다; 전시",             pos: "v/n" },
  { word: "explicit",      pron: "[ɪksplɪ́sɪt]",       meaning: "명시적인, 명백한",           pos: "adj" },
  { word: "facilitate",    pron: "[fəsɪ́lɪteɪt]",      meaning: "촉진하다, 용이하게 하다",     pos: "v" },
  { word: "factor",        pron: "[fǽktər]",          meaning: "요인, 요소",                pos: "n" },
  { word: "fluctuate",     pron: "[flʌ́ktʃueɪt]",      meaning: "변동하다",                  pos: "v" },
  { word: "focus",         pron: "[fóʊkəs]",          meaning: "집중하다; 초점",             pos: "v/n" },
  { word: "function",      pron: "[fʌ́ŋkʃən]",         meaning: "기능; 기능하다",             pos: "n/v" },
  { word: "fundamental",   pron: "[ˌfʌndəméntəl]",    meaning: "근본적인, 기본적인",          pos: "adj" },
  { word: "generate",      pron: "[dʒénəreɪt]",       meaning: "발생시키다, 만들어내다",       pos: "v" },
  { word: "global",        pron: "[ɡlóʊbəl]",         meaning: "전 세계적인, 포괄적인",       pos: "adj" },
  { word: "gradual",       pron: "[ɡrǽdʒuəl]",        meaning: "점진적인",                  pos: "adj" },
  { word: "hypothesis",    pron: "[haɪpɒ́θəsɪs]",      meaning: "가설",                     pos: "n" },
  { word: "identify",      pron: "[aɪdéntɪfaɪ]",      meaning: "확인하다, 식별하다",          pos: "v" },
  { word: "illustrate",    pron: "[ɪ́ləstreɪt]",        meaning: "설명하다, 예시하다",          pos: "v" },
  { word: "implement",     pron: "[ɪ́mplɪment]",        meaning: "시행하다, 구현하다",          pos: "v" },
  { word: "imply",         pron: "[ɪmpláɪ]",          meaning: "암시하다, 내포하다",          pos: "v" },
  { word: "impose",        pron: "[ɪmpóʊz]",          meaning: "부과하다, 강요하다",          pos: "v" },
  { word: "indicate",      pron: "[ɪ́ndɪkeɪt]",        meaning: "나타내다, 지적하다",          pos: "v" },
  { word: "infer",         pron: "[ɪnfɜ́ːr]",          meaning: "추론하다",                  pos: "v" },
  { word: "inherent",      pron: "[ɪnhɪ́ərənt]",       meaning: "고유한, 내재하는",           pos: "adj" },
  { word: "initiate",      pron: "[ɪnɪ́ʃieɪt]",        meaning: "시작하다, 착수하다",          pos: "v" },
  { word: "integrate",     pron: "[ɪ́ntɪɡreɪt]",       meaning: "통합하다",                  pos: "v" },
  { word: "interpret",     pron: "[ɪntɜːrprɪ́t]",      meaning: "해석하다",                  pos: "v" },
  { word: "investigate",   pron: "[ɪnvéstɪɡeɪt]",     meaning: "조사하다",                  pos: "v" },
  { word: "involve",       pron: "[ɪnvɒ́lv]",          meaning: "포함하다, 관련되다",          pos: "v" },
  { word: "isolate",       pron: "[áɪsəleɪt]",        meaning: "격리하다, 분리하다",          pos: "v" },
  { word: "justify",       pron: "[dʒʌ́stɪfaɪ]",       meaning: "정당화하다",                pos: "v" },
  { word: "legitimate",    pron: "[lɪdʒɪ́tɪmɪt]",      meaning: "합법적인, 정당한",           pos: "adj" },
  { word: "linear",        pron: "[lɪ́niər]",          meaning: "선형의, 직선의",             pos: "adj" },
  { word: "maintain",      pron: "[meɪntéɪn]",        meaning: "유지하다, 주장하다",          pos: "v" },
  { word: "manipulate",    pron: "[mənɪ́pjuleɪt]",     meaning: "조종하다, 조작하다",          pos: "v" },
  { word: "maximum",       pron: "[mǽksɪməm]",        meaning: "최대의; 최대값",             pos: "adj/n" },
  { word: "mechanism",     pron: "[mékənɪzəm]",       meaning: "메커니즘, 기구",             pos: "n" },
  { word: "minimize",      pron: "[mɪ́nɪmaɪz]",        meaning: "최소화하다",                pos: "v" },
  { word: "modify",        pron: "[mɒ́dɪfaɪ]",         meaning: "수정하다, 변형하다",          pos: "v" },
  { word: "monitor",       pron: "[mɒ́nɪtər]",         meaning: "감시하다; 모니터",           pos: "v/n" },
  { word: "motivate",      pron: "[móʊtɪveɪt]",       meaning: "동기부여하다",               pos: "v" },
  { word: "notion",        pron: "[nóʊʃən]",          meaning: "개념, 관념",                pos: "n" },
  { word: "obtain",        pron: "[əbtéɪn]",          meaning: "얻다, 획득하다",             pos: "v" },
  { word: "obvious",       pron: "[ɒ́bviəs]",          meaning: "명백한, 분명한",             pos: "adj" },
  { word: "occupy",        pron: "[ɒ́kjupaɪ]",         meaning: "차지하다, 점령하다",          pos: "v" },
  { word: "occur",         pron: "[əkɜ́ːr]",           meaning: "발생하다, 일어나다",          pos: "v" },
  { word: "oppose",        pron: "[əpóʊz]",           meaning: "반대하다",                  pos: "v" },
  { word: "overcome",      pron: "[ˌoʊvərkʌ́m]",       meaning: "극복하다",                  pos: "v" },
  { word: "perceive",      pron: "[pərsíːv]",         meaning: "인식하다, 지각하다",          pos: "v" },
  { word: "persist",       pron: "[pərsɪ́st]",         meaning: "지속하다, 고집하다",          pos: "v" },
  { word: "phenomenon",    pron: "[fɪnɒ́mɪnɒn]",       meaning: "현상",                     pos: "n" },
  { word: "potential",     pron: "[pəténʃəl]",        meaning: "잠재적인; 잠재력",           pos: "adj/n" },
  { word: "predict",       pron: "[prɪdɪ́kt]",         meaning: "예측하다",                  pos: "v" },
  { word: "predominant",   pron: "[prɪdɒ́mɪnənt]",     meaning: "지배적인, 현저한",           pos: "adj" },
  { word: "preserve",      pron: "[prɪzɜ́ːrv]",        meaning: "보존하다",                  pos: "v" },
  { word: "prevail",       pron: "[prɪvéɪl]",         meaning: "만연하다, 우세하다",          pos: "v" },
  { word: "principle",     pron: "[prɪ́nsɪpəl]",       meaning: "원칙, 원리",                pos: "n" },
  { word: "process",       pron: "[próʊses]",         meaning: "과정; 처리하다",             pos: "n/v" },
  { word: "prohibit",      pron: "[prəhɪ́bɪt]",        meaning: "금지하다",                  pos: "v" },
  { word: "promote",       pron: "[prəmóʊt]",         meaning: "촉진하다, 홍보하다",          pos: "v" },
  { word: "rational",      pron: "[rǽʃənəl]",         meaning: "이성적인, 합리적인",          pos: "adj" },
  { word: "reduce",        pron: "[rɪdjúːs]",         meaning: "줄이다, 감소시키다",          pos: "v" },
  { word: "reinforce",     pron: "[ˌriːɪnfɔ́ːrs]",     meaning: "강화하다",                  pos: "v" },
  { word: "relevant",      pron: "[réləvənt]",        meaning: "관련된, 적절한",             pos: "adj" },
  { word: "resolve",       pron: "[rɪzɒ́lv]",          meaning: "해결하다, 결심하다",          pos: "v" },
  { word: "respond",       pron: "[rɪspɒ́nd]",         meaning: "반응하다, 답하다",           pos: "v" },
  { word: "restrict",      pron: "[rɪstrɪ́kt]",        meaning: "제한하다",                  pos: "v" },
  { word: "reveal",        pron: "[rɪvíːl]",          meaning: "드러내다, 밝히다",           pos: "v" },
  { word: "severe",        pron: "[sɪvɪ́ər]",          meaning: "심각한, 가혹한",             pos: "adj" },
  { word: "significant",   pron: "[sɪɡnɪ́fɪkənt]",     meaning: "중요한, 상당한",             pos: "adj" },
  { word: "simulate",      pron: "[sɪ́mjuleɪt]",       meaning: "모방하다, 시뮬레이션하다",    pos: "v" },
  { word: "specific",      pron: "[spəsɪ́fɪk]",        meaning: "구체적인, 특정한",           pos: "adj" },
  { word: "stable",        pron: "[stéɪbəl]",         meaning: "안정적인",                  pos: "adj" },
  { word: "strategy",      pron: "[strǽtədʒi]",       meaning: "전략",                     pos: "n" },
  { word: "subsequent",    pron: "[sʌ́bsɪkwənt]",      meaning: "그 다음의, 뒤따르는",        pos: "adj" },
  { word: "substitute",    pron: "[sʌ́bstɪtjuːt]",     meaning: "대체하다; 대체물",           pos: "v/n" },
  { word: "sufficient",    pron: "[səfɪ́ʃənt]",        meaning: "충분한",                   pos: "adj" },
  { word: "summarize",     pron: "[sʌ́məraɪz]",        meaning: "요약하다",                  pos: "v" },
  { word: "suppress",      pron: "[səprés]",          meaning: "억압하다, 억제하다",          pos: "v" },
  { word: "sustain",       pron: "[səstéɪn]",         meaning: "지속하다, 지탱하다",          pos: "v" },
  { word: "terminate",     pron: "[tɜːrmɪ́neɪt]",      meaning: "종료하다, 끝내다",           pos: "v" },
  { word: "theory",        pron: "[θɪ́əri]",           meaning: "이론",                     pos: "n" },
  { word: "transform",     pron: "[trænsfɔ́ːrm]",       meaning: "변환하다, 변형하다",          pos: "v" },
  { word: "transmit",      pron: "[trænsmɪ́t]",        meaning: "전달하다, 전송하다",          pos: "v" },
  { word: "transparent",   pron: "[trænspǽrənt]",      meaning: "투명한, 명확한",             pos: "adj" },
  { word: "trigger",       pron: "[trɪ́ɡər]",          meaning: "유발하다; 방아쇠",           pos: "v/n" },
  { word: "undermine",     pron: "[ˌʌndərmáɪn]",      meaning: "약화시키다",                pos: "v" },
  { word: "utilize",       pron: "[júːtɪlaɪz]",       meaning: "활용하다",                  pos: "v" },
  { word: "valid",         pron: "[vǽlɪd]",           meaning: "유효한, 타당한",             pos: "adj" },
  { word: "vary",          pron: "[véəri]",           meaning: "다양하다, 변하다",           pos: "v" },
  { word: "verify",        pron: "[vérɪfaɪ]",         meaning: "확인하다, 검증하다",          pos: "v" },
  { word: "vital",         pron: "[váɪtəl]",          meaning: "필수적인, 매우 중요한",       pos: "adj" },
  { word: "vulnerable",    pron: "[vʌ́lnərəbəl]",      meaning: "취약한",                   pos: "adj" },
  { word: "abolition",     pron: "[ˌæbəlɪ́ʃən]",       meaning: "폐지",                     pos: "n" },
  { word: "abundance",     pron: "[əbʌ́ndəns]",        meaning: "풍부함",                   pos: "n" },
  { word: "accumulate",    pron: "[əkjúːmjuleɪt]",    meaning: "축적하다",                  pos: "v" },
  { word: "acute",         pron: "[əkjúːt]",          meaning: "급성의, 날카로운",           pos: "adj" },
  { word: "affection",     pron: "[əfékʃən]",         meaning: "애정",                     pos: "n" },
  { word: "aggravate",     pron: "[ǽɡrəveɪt]",        meaning: "악화시키다",                pos: "v" },
  { word: "aggressive",    pron: "[əɡrésɪv]",         meaning: "공격적인",                  pos: "adj" },
  { word: "ambition",      pron: "[æmbɪ́ʃən]",         meaning: "야망",                     pos: "n" },
  { word: "amend",         pron: "[əménd]",           meaning: "수정하다, 개정하다",          pos: "v" },
  { word: "analogy",       pron: "[ənǽlədʒi]",        meaning: "유추, 비유",                pos: "n" },
  { word: "arduous",       pron: "[ɑ́ːrdʒuəs]",        meaning: "힘든, 어려운",              pos: "adj" },
  { word: "articulate",    pron: "[ɑːrtɪ́kjuleɪt]",    meaning: "명확히 표현하다; 명확한",    pos: "v/adj" },
  { word: "aspire",        pron: "[əspáɪər]",         meaning: "열망하다",                  pos: "v" },
  { word: "authoritative", pron: "[ɔːθɒ́rɪtətɪv]",     meaning: "권위 있는",                 pos: "adj" },
  { word: "avert",         pron: "[əvɜ́ːrt]",          meaning: "막다, 피하다",              pos: "v" },
  { word: "benevolent",    pron: "[bɪnévələnt]",       meaning: "자비로운, 친절한",           pos: "adj" },
  { word: "bizarre",       pron: "[bɪzɑ́ːr]",          meaning: "기이한, 이상한",             pos: "adj" },
  { word: "candid",        pron: "[kǽndɪd]",          meaning: "솔직한",                   pos: "adj" },
  { word: "cautious",      pron: "[kɔ́ːʃəs]",          meaning: "조심스러운",                pos: "adj" },
  { word: "circumstance",  pron: "[sɜːrkə́mstæns]",    meaning: "상황, 환경",                pos: "n" },
  { word: "cognitive",     pron: "[kɒ́ɡnɪtɪv]",        meaning: "인지적인",                  pos: "adj" },
  { word: "compassion",    pron: "[kəmpǽʃən]",        meaning: "연민, 동정심",              pos: "n" },
  { word: "compel",        pron: "[kəmpél]",          meaning: "강요하다",                  pos: "v" },
  { word: "concede",       pron: "[kənsíːd]",         meaning: "인정하다, 양보하다",          pos: "v" },
  { word: "condense",      pron: "[kəndéns]",         meaning: "압축하다, 요약하다",          pos: "v" },
  { word: "confine",       pron: "[kənfáɪn]",         meaning: "제한하다, 가두다",           pos: "v" },
  { word: "conscious",     pron: "[kɒ́nʃəs]",          meaning: "의식하는, 의식이 있는",      pos: "adj" },
  { word: "consensus",     pron: "[kənsénsəs]",       meaning: "합의, 의견 일치",            pos: "n" },
  { word: "contemplate",   pron: "[kɒ́ntəmpleɪt]",     meaning: "심사숙고하다",               pos: "v" },
  { word: "contradict",    pron: "[ˌkɒntrədɪ́kt]",     meaning: "모순되다, 반박하다",          pos: "v" },
  { word: "convince",      pron: "[kənvɪ́ns]",         meaning: "납득시키다",                pos: "v" },
  { word: "corrupt",       pron: "[kərʌ́pt]",          meaning: "부패한; 부패시키다",          pos: "adj/v" },
  { word: "counterpart",   pron: "[káʊntərpɑːrt]",    meaning: "대응하는 것, 상대방",        pos: "n" },
  { word: "cultivate",     pron: "[kʌ́ltɪveɪt]",       meaning: "경작하다, 계발하다",          pos: "v" },
  { word: "cynical",       pron: "[sɪ́nɪkəl]",         meaning: "냉소적인",                  pos: "adj" },
  { word: "decay",         pron: "[dɪkéɪ]",           meaning: "부패하다; 부패",             pos: "v/n" },
  { word: "decisive",      pron: "[dɪsáɪsɪv]",        meaning: "결정적인, 단호한",           pos: "adj" },
  { word: "dedicate",      pron: "[dédɪkeɪt]",        meaning: "헌신하다, 바치다",           pos: "v" },
  { word: "deficiency",    pron: "[dɪfɪ́ʃənsi]",       meaning: "결핍, 부족",                pos: "n" },
  { word: "deliberate",    pron: "[dɪlɪ́bərɪt]",       meaning: "신중한; 숙고하다",           pos: "adj/v" },
  { word: "deprive",       pron: "[dɪpráɪv]",         meaning: "빼앗다, 박탈하다",           pos: "v" },
  { word: "desire",        pron: "[dɪzáɪər]",         meaning: "바라다; 욕망",              pos: "v/n" },
  { word: "deteriorate",   pron: "[dɪtɪ́əriəreɪt]",    meaning: "악화되다",                  pos: "v" },
  { word: "deviate",       pron: "[díːvieɪt]",        meaning: "벗어나다",                  pos: "v" },
  { word: "diligent",      pron: "[dɪ́lɪdʒənt]",       meaning: "부지런한",                  pos: "adj" },
  { word: "disclose",      pron: "[dɪsklóʊz]",        meaning: "폭로하다, 공개하다",          pos: "v" },
  { word: "discriminate",  pron: "[dɪskrɪ́mɪneɪt]",    meaning: "차별하다, 구별하다",          pos: "v" },
  { word: "dismiss",       pron: "[dɪsmɪ́s]",          meaning: "묵살하다, 해고하다",          pos: "v" },
  { word: "disparity",     pron: "[dɪspǽrɪti]",       meaning: "불평등, 차이",              pos: "n" },
  { word: "disrupt",       pron: "[dɪsrʌ́pt]",         meaning: "방해하다, 붕괴시키다",        pos: "v" },
  { word: "distinguish",   pron: "[dɪstɪ́ŋɡwɪʃ]",      meaning: "구별하다",                  pos: "v" },
  { word: "distribute",    pron: "[dɪstrɪ́bjuːt]",     meaning: "분배하다, 배포하다",          pos: "v" },
  { word: "dominate",      pron: "[dɒ́mɪneɪt]",        meaning: "지배하다",                  pos: "v" },
  { word: "durable",       pron: "[djʊ́ərəbəl]",       meaning: "내구성이 있는",              pos: "adj" },
  { word: "eager",         pron: "[íːɡər]",           meaning: "열망하는, 간절히 바라는",     pos: "adj" },
  { word: "emit",          pron: "[ɪmɪ́t]",            meaning: "방출하다, 내뿜다",           pos: "v" },
  { word: "emphasize",     pron: "[émfəsaɪz]",        meaning: "강조하다",                  pos: "v" },
  { word: "empirical",     pron: "[ɪmpɪ́rɪkəl]",       meaning: "경험적인, 실증적인",          pos: "adj" },
  { word: "endure",        pron: "[ɪndjʊ́ər]",         meaning: "견디다, 지속되다",           pos: "v" },
  { word: "enforce",       pron: "[ɪnfɔ́ːrs]",         meaning: "집행하다, 강제하다",          pos: "v" },
  { word: "enthusiastic",  pron: "[ɪnˌθjuːziǽstɪk]",  meaning: "열정적인",                  pos: "adj" },
  { word: "equip",         pron: "[ɪkwɪ́p]",           meaning: "장비를 갖추다",              pos: "v" },
  { word: "equivalent",    pron: "[ɪkwɪ́vələnt]",      meaning: "동등한; 동등물",             pos: "adj/n" },
  { word: "estimate",      pron: "[éstɪmɪt]",         meaning: "추정하다; 추정",             pos: "v/n" },
  { word: "excessive",     pron: "[ɪksésɪv]",         meaning: "과도한",                   pos: "adj" },
  { word: "exhaust",       pron: "[ɪɡzɔ́ːst]",         meaning: "고갈시키다, 지치게 하다",     pos: "v" },
  { word: "expand",        pron: "[ɪkspǽnd]",         meaning: "확장하다",                  pos: "v" },
  { word: "exploit",       pron: "[ɪksplɔ́ɪt]",        meaning: "이용하다, 착취하다",          pos: "v" },
  { word: "expose",        pron: "[ɪkspóʊz]",         meaning: "노출시키다, 폭로하다",        pos: "v" },
  { word: "exquisite",     pron: "[ɪkskwɪ́zɪt]",       meaning: "정교한, 절묘한",             pos: "adj" },
  { word: "extensive",     pron: "[ɪksténsɪv]",       meaning: "광범위한",                  pos: "adj" },
  { word: "extraordinary", pron: "[ɪkstrɔ́ːrdɪneri]",  meaning: "비범한, 놀라운",             pos: "adj" },
  { word: "feasible",      pron: "[fíːzɪbəl]",        meaning: "실행 가능한",               pos: "adj" },
  { word: "flexible",      pron: "[fléksɪbəl]",       meaning: "유연한",                   pos: "adj" },
  { word: "flourish",      pron: "[flʌ́rɪʃ]",          meaning: "번창하다",                  pos: "v" },
  { word: "formulate",     pron: "[fɔ́ːrmjuleɪt]",     meaning: "공식화하다, 만들어내다",       pos: "v" },
  { word: "foster",        pron: "[fɒ́stər]",          meaning: "육성하다, 조장하다",          pos: "v" },
  { word: "fragile",       pron: "[frǽdʒaɪl]",        meaning: "깨지기 쉬운, 취약한",        pos: "adj" },
  { word: "frequent",      pron: "[fríːkwənt]",       meaning: "빈번한",                   pos: "adj" },
  { word: "genuine",       pron: "[dʒénjuɪn]",        meaning: "진짜의, 진심의",             pos: "adj" },
  { word: "harmony",       pron: "[hɑ́ːrməni]",        meaning: "조화",                     pos: "n" },
  { word: "hierarchy",     pron: "[háɪərɑːrki]",      meaning: "계층 구조",                 pos: "n" },
  { word: "hostile",       pron: "[hɒ́staɪl]",         meaning: "적대적인",                  pos: "adj" },
  { word: "ideal",         pron: "[aɪdíːəl]",         meaning: "이상적인; 이상",             pos: "adj/n" },
  { word: "ignore",        pron: "[ɪɡnɔ́ːr]",          meaning: "무시하다",                  pos: "v" },
  { word: "immense",       pron: "[ɪméns]",           meaning: "거대한, 막대한",             pos: "adj" },
  { word: "immune",        pron: "[ɪmjúːn]",          meaning: "면역의, 영향을 받지 않는",   pos: "adj" },
  { word: "implicit",      pron: "[ɪmplɪ́sɪt]",        meaning: "암묵적인",                  pos: "adj" },
  { word: "inadequate",    pron: "[ɪnǽdɪkwɪt]",       meaning: "불충분한",                  pos: "adj" },
  { word: "inevitable",    pron: "[ɪnévɪtəbəl]",      meaning: "불가피한",                  pos: "adj" },
  { word: "influence",     pron: "[ɪ́nfluəns]",        meaning: "영향; 영향을 미치다",         pos: "n/v" },
  { word: "instinct",      pron: "[ɪ́nstɪŋkt]",        meaning: "본능",                     pos: "n" },
  { word: "intense",       pron: "[ɪnténs]",          meaning: "강렬한",                   pos: "adj" },
  { word: "intrinsic",     pron: "[ɪntrɪ́nsɪk]",       meaning: "본질적인, 고유의",           pos: "adj" },
  { word: "irrelevant",    pron: "[ɪréləvənt]",       meaning: "관련 없는",                 pos: "adj" },
  { word: "launch",        pron: "[lɔːntʃ]",           meaning: "시작하다, 출시하다",          pos: "v" },
  { word: "marginal",      pron: "[mɑ́ːrdʒɪnəl]",      meaning: "미미한, 주변적인",           pos: "adj" },
  { word: "merit",         pron: "[mérɪt]",           meaning: "장점, 가치; ~을 받을 만하다", pos: "n/v" },
  { word: "mutual",        pron: "[mjúːtʃuəl]",       meaning: "상호의",                   pos: "adj" },
  { word: "neglect",       pron: "[nɪɡlékt]",         meaning: "무시하다, 방치하다",          pos: "v" },
  { word: "neutral",       pron: "[njúːtrəl]",        meaning: "중립적인",                  pos: "adj" },
  { word: "obscure",       pron: "[əbskjʊ́ər]",        meaning: "모호한; 가리다",             pos: "adj/v" },
  { word: "obstacle",      pron: "[ɒ́bstəkəl]",        meaning: "장애물",                   pos: "n" },
  { word: "optimistic",    pron: "[ˌɒptɪmɪ́stɪk]",     meaning: "낙관적인",                  pos: "adj" },
  { word: "outcome",       pron: "[áʊtkʌm]",          meaning: "결과",                     pos: "n" },
  { word: "overwhelm",     pron: "[ˌoʊvərwélm]",      meaning: "압도하다",                  pos: "v" },
  { word: "paradox",       pron: "[pǽrədɒks]",        meaning: "역설",                     pos: "n" },
  { word: "participate",   pron: "[pɑːrtɪ́sɪpeɪt]",    meaning: "참가하다",                  pos: "v" },
  { word: "passive",       pron: "[pǽsɪv]",           meaning: "수동적인",                  pos: "adj" },
  { word: "peculiar",      pron: "[pɪkjúːliər]",      meaning: "독특한, 이상한",             pos: "adj" },
  { word: "permanent",     pron: "[pɜːrmə́nənt]",      meaning: "영구적인",                  pos: "adj" },
  { word: "persuade",      pron: "[pərswéɪd]",        meaning: "설득하다",                  pos: "v" },
  { word: "pragmatic",     pron: "[præɡmǽtɪk]",       meaning: "실용적인",                  pos: "adj" },
  { word: "precise",       pron: "[prɪsáɪs]",         meaning: "정확한",                   pos: "adj" },
  { word: "preference",    pron: "[préfərəns]",       meaning: "선호",                     pos: "n" },
  { word: "premise",       pron: "[prémɪs]",          meaning: "전제",                     pos: "n" },
  { word: "priority",      pron: "[praɪɒ́rɪti]",       meaning: "우선순위",                  pos: "n" },
  { word: "profound",      pron: "[prəfáʊnd]",        meaning: "심오한, 깊은",              pos: "adj" },
  { word: "prominent",     pron: "[prɒ́mɪnənt]",       meaning: "두드러진, 저명한",           pos: "adj" },
  { word: "proportion",    pron: "[prəpɔ́ːrʃən]",      meaning: "비율, 균형",                pos: "n" },
  { word: "pursue",        pron: "[pərsjúː]",         meaning: "추구하다",                  pos: "v" },
  { word: "radical",       pron: "[rǽdɪkəl]",         meaning: "급진적인, 근본적인",          pos: "adj" },
  { word: "random",        pron: "[rǽndəm]",          meaning: "무작위의",                  pos: "adj" },
  { word: "refine",        pron: "[rɪfáɪn]",          meaning: "정제하다, 개선하다",          pos: "v" },
  { word: "regardless",    pron: "[rɪɡɑ́ːrdlɪs]",      meaning: "~에 관계없이",              pos: "adv" },
  { word: "reluctant",     pron: "[rɪlʌ́ktənt]",       meaning: "꺼리는, 마지못한",           pos: "adj" },
  { word: "remedy",        pron: "[rémədi]",          meaning: "치료법; 고치다",             pos: "n/v" },
  { word: "resemble",      pron: "[rɪzémbəl]",        meaning: "닮다, 비슷하다",             pos: "v" },
  { word: "resilient",     pron: "[rɪzɪ́liənt]",       meaning: "회복력 있는",               pos: "adj" },
  { word: "retain",        pron: "[rɪtéɪn]",          meaning: "유지하다, 보유하다",          pos: "v" },
  { word: "rigid",         pron: "[rɪ́dʒɪd]",          meaning: "엄격한, 딱딱한",             pos: "adj" },
  { word: "robust",        pron: "[roʊbʌ́st]",         meaning: "강건한, 튼튼한",             pos: "adj" },
  { word: "scarce",        pron: "[skeərs]",           meaning: "부족한, 희귀한",             pos: "adj" },
  { word: "scrutinize",    pron: "[skrúːtɪnaɪz]",     meaning: "면밀히 조사하다",            pos: "v" },
  { word: "skeptical",     pron: "[sképtɪkəl]",       meaning: "회의적인",                  pos: "adj" },
  { word: "spontaneous",   pron: "[spɒntéɪniəs]",     meaning: "자발적인, 즉흥적인",          pos: "adj" },
  { word: "subtle",        pron: "[sʌ́təl]",           meaning: "미묘한",                   pos: "adj" },
  { word: "superficial",   pron: "[ˌsuːpərfɪ́ʃəl]",    meaning: "피상적인, 표면적인",          pos: "adj" },
  { word: "surplus",       pron: "[sɜːrplə́s]",        meaning: "잉여, 과잉",                pos: "n" },
  { word: "swift",         pron: "[swɪft]",            meaning: "빠른",                     pos: "adj" },
  { word: "tend",          pron: "[tend]",             meaning: "~하는 경향이 있다",          pos: "v" },
  { word: "tolerate",      pron: "[tɒ́ləreɪt]",        meaning: "용인하다, 참다",             pos: "v" },
  { word: "transition",    pron: "[trænzɪ́ʃən]",       meaning: "전환, 이행",                pos: "n" },
  { word: "typical",       pron: "[tɪ́pɪkəl]",         meaning: "전형적인",                  pos: "adj" },
  { word: "ultimate",      pron: "[ʌ́ltɪmɪt]",         meaning: "궁극적인",                  pos: "adj" },
  { word: "unanimous",     pron: "[juːnǽnɪməs]",      meaning: "만장일치의",                pos: "adj" },
  { word: "uniform",       pron: "[júːnɪfɔːrm]",      meaning: "균일한; 제복",              pos: "adj/n" },
  { word: "unique",        pron: "[juːníːk]",         meaning: "독특한, 유일한",             pos: "adj" },
  { word: "universal",     pron: "[ˌjuːnɪvɜːrsə́l]",   meaning: "보편적인",                  pos: "adj" },
  { word: "unprecedented", pron: "[ʌnprésɪdentɪd]",   meaning: "전례 없는",                 pos: "adj" },
  { word: "vague",         pron: "[veɪɡ]",             meaning: "모호한, 불명확한",           pos: "adj" },
  { word: "vigorous",      pron: "[vɪ́ɡərəs]",         meaning: "활발한, 강력한",             pos: "adj" },
  { word: "volatile",      pron: "[vɒ́lətaɪl]",        meaning: "불안정한, 변덕스러운",        pos: "adj" },
  { word: "widespread",    pron: "[wáɪdspred]",       meaning: "광범위한, 널리 퍼진",        pos: "adj" },
  { word: "incentive",     pron: "[ɪnséntɪv]",        meaning: "동기, 유인책",              pos: "n" },
  { word: "stimulate",     pron: "[stɪ́mjuleɪt]",      meaning: "자극하다",                  pos: "v" },
  { word: "catastrophe",   pron: "[kətǽstrəfi]",      meaning: "대재앙",                   pos: "n" },
  { word: "conceal",       pron: "[kənsíːl]",         meaning: "숨기다, 감추다",             pos: "v" },
  { word: "deplete",       pron: "[dɪplíːt]",         meaning: "고갈시키다",                pos: "v" },
  { word: "envision",      pron: "[ɪnvɪ́ʒən]",         meaning: "마음속에 그리다",            pos: "v" },
  { word: "erode",         pron: "[ɪróʊd]",           meaning: "침식하다, 약화시키다",        pos: "v" },
  { word: "exaggerate",    pron: "[ɪɡzǽdʒəreɪt]",     meaning: "과장하다",                  pos: "v" },
  { word: "hesitate",      pron: "[hézɪteɪt]",        meaning: "망설이다",                  pos: "v" },
  { word: "illuminate",    pron: "[ɪlúːmɪneɪt]",      meaning: "밝히다, 설명하다",           pos: "v" },
  { word: "impede",        pron: "[ɪmpíːd]",          meaning: "방해하다",                  pos: "v" },
  { word: "inspire",       pron: "[ɪnspáɪər]",        meaning: "영감을 주다",               pos: "v" },
  { word: "logical",       pron: "[lɒ́dʒɪkəl]",        meaning: "논리적인",                  pos: "adj" },
  { word: "migrate",       pron: "[máɪɡreɪt]",        meaning: "이주하다",                  pos: "v" },
  { word: "narrative",     pron: "[nǽrətɪv]",         meaning: "서술, 이야기",              pos: "n" },
  { word: "objective",     pron: "[əbdʒéktɪv]",       meaning: "객관적인; 목표",             pos: "adj/n" },
  { word: "regulate",      pron: "[réɡjuleɪt]",       meaning: "규제하다",                  pos: "v" },
  { word: "sequence",      pron: "[síːkwəns]",        meaning: "순서, 연속",                pos: "n" },
  { word: "stereotype",    pron: "[stériətaɪp]",      meaning: "고정관념; 고정화하다",        pos: "n/v" },
  { word: "subjective",    pron: "[səbdʒéktɪv]",      meaning: "주관적인",                  pos: "adj" },
  { word: "tendency",      pron: "[téndənsi]",        meaning: "경향",                     pos: "n" },
  { word: "whereas",       pron: "[wɛrǽz]",           meaning: "반면에",                   pos: "conj" },
  { word: "yield",         pron: "[jiːld]",            meaning: "산출하다; 수익",             pos: "v/n" },
]
