-- ============================================================
-- 전산매체 레이아웃 관리 테이블 (YTTS DB)
-- ============================================================

-- ============================================================
-- 기존 테이블 삭제 (재생성 시 실행)
-- FK 자식 테이블부터 순서대로 DROP
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_ITEM_NOTE      CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_TAX_CODE_EDIT  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_TAX_ITEM_EDIT  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_JAVA_CODE_EDIT CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_HWP_PARSE_LOG  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_TAX_JAVA_MAP   CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_COMPARE        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_SECT_CONFIG    CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_TAX            CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_JAVA           CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_HWP_FILE       CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MLAY_JAVA_FILE      CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- 기반 테이블
-- ============================================================

-- HWP 업로드 (귀속연도+사용자 1건, 재업로드 시 덮어쓰기)
CREATE TABLE MLAY_HWP_FILE (
  YEAR          NUMBER(4)       NOT NULL,
  USER_ID       NUMBER          NOT NULL,
  HWP_FILE_NAME VARCHAR2(200),
  HWP_FILE_PATH VARCHAR2(500),
  HWP_DATA      BLOB,
  ROW_COUNT     NUMBER          DEFAULT 0,
  UPLOADED_AT   DATE            DEFAULT SYSDATE NOT NULL,
  NOTE          VARCHAR2(200),
  CONSTRAINT PK_MLAY_HWP_FILE      PRIMARY KEY (YEAR, USER_ID),
  CONSTRAINT FK_MLAY_HWP_FILE_USER FOREIGN KEY (USER_ID) REFERENCES YTTS_USERS (USER_ID)
);

COMMENT ON TABLE  MLAY_HWP_FILE               IS '국세청 전산매체 HWP 업로드 (귀속연도+사용자 1건, 재업로드 시 덮어쓰기)';
COMMENT ON COLUMN MLAY_HWP_FILE.YEAR          IS '귀속연도 (예: 2025)';
COMMENT ON COLUMN MLAY_HWP_FILE.USER_ID       IS '업로드한 사용자 (YTTS_USERS.USER_ID)';
COMMENT ON COLUMN MLAY_HWP_FILE.HWP_FILE_NAME IS '업로드한 HWP 파일명';
COMMENT ON COLUMN MLAY_HWP_FILE.HWP_FILE_PATH IS '업로드한 HWP 파일 경로';
COMMENT ON COLUMN MLAY_HWP_FILE.HWP_DATA      IS 'HWP 파일 원본 (재파싱용)';
COMMENT ON COLUMN MLAY_HWP_FILE.ROW_COUNT     IS '파싱된 전체 항목 수';
COMMENT ON COLUMN MLAY_HWP_FILE.UPLOADED_AT   IS '업로드 일시';
COMMENT ON COLUMN MLAY_HWP_FILE.NOTE          IS '비고';

-- Java 소스 업로드 (귀속연도+사용자 1건, 재업로드 시 덮어쓰기)
-- MLAY_HWP_FILE와 독립적 — 입력 순서 무관, 상호 재업로드 영향 없음
CREATE TABLE MLAY_JAVA_FILE (
  YEAR           NUMBER(4)       NOT NULL,
  USER_ID        NUMBER          NOT NULL,
  JAVA_FILE_NAME VARCHAR2(200),
  JAVA_FILE_PATH VARCHAR2(500),
  JAVA_DATA      CLOB,
  ROW_COUNT      NUMBER          DEFAULT 0,
  UPLOADED_AT    DATE            DEFAULT SYSDATE NOT NULL,
  NOTE           VARCHAR2(200),
  CONSTRAINT PK_MLAY_JAVA_FILE   PRIMARY KEY (YEAR, USER_ID),
  CONSTRAINT FK_MLAY_JFILE_USER FOREIGN KEY (USER_ID) REFERENCES YTTS_USERS (USER_ID)
);

COMMENT ON TABLE  MLAY_JAVA_FILE                IS 'Java 소스 업로드 (귀속연도+사용자 1건, 재업로드 시 덮어쓰기)';
COMMENT ON COLUMN MLAY_JAVA_FILE.YEAR           IS '귀속연도 (예: 2025)';
COMMENT ON COLUMN MLAY_JAVA_FILE.USER_ID        IS '업로드한 사용자 (YTTS_USERS.USER_ID)';
COMMENT ON COLUMN MLAY_JAVA_FILE.JAVA_FILE_NAME IS '업로드한 Java 파일명';
COMMENT ON COLUMN MLAY_JAVA_FILE.JAVA_FILE_PATH IS '업로드한 Java 파일 경로';
COMMENT ON COLUMN MLAY_JAVA_FILE.JAVA_DATA      IS 'Java 소스 원본 (재파싱용)';
COMMENT ON COLUMN MLAY_JAVA_FILE.ROW_COUNT      IS '파싱된 전체 필드 수';
COMMENT ON COLUMN MLAY_JAVA_FILE.UPLOADED_AT    IS '업로드 일시';
COMMENT ON COLUMN MLAY_JAVA_FILE.NOTE           IS '비고';

-- 국세청 레이아웃 (HWP 파싱 결과)
CREATE TABLE MLAY_TAX (
  YEAR        NUMBER(4)       NOT NULL,
  USER_ID     NUMBER          NOT NULL,
  SEQ         NUMBER          NOT NULL,
  RECORD_TYPE VARCHAR2(1),
  GUBUN       VARCHAR2(200),
  CODE        VARCHAR2(10)    NOT NULL,
  ITEM        VARCHAR2(200),
  VAL         VARCHAR2(50),
  FIELD_TYPE  VARCHAR2(1),
  FIELD_LEN   NUMBER,
  HWP_CUM     NUMBER,
  SECT        VARCHAR2(10)    DEFAULT 'BODY_1',
  CONSTRAINT PK_MLAY_TAX PRIMARY KEY (YEAR, USER_ID, SEQ),
  CONSTRAINT FK_MLAY_TAX  FOREIGN KEY (YEAR, USER_ID) REFERENCES MLAY_HWP_FILE (YEAR, USER_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  MLAY_TAX             IS '국세청 전산매체 레이아웃 (HWP 파싱 결과)';
COMMENT ON COLUMN MLAY_TAX.YEAR        IS '귀속연도';
COMMENT ON COLUMN MLAY_TAX.USER_ID     IS '업로드한 사용자';
COMMENT ON COLUMN MLAY_TAX.SEQ         IS '원본 행 순서 (1-based)';
COMMENT ON COLUMN MLAY_TAX.RECORD_TYPE IS '레코드 구분 (A~K), CODE 첫 글자';
COMMENT ON COLUMN MLAY_TAX.GUBUN       IS 'HWP 구분 컬럼 원본값 (예: 【소득공제명세의 인적사항1】)';
COMMENT ON COLUMN MLAY_TAX.CODE        IS '항목코드 (예: A1, C5)';
COMMENT ON COLUMN MLAY_TAX.ITEM        IS '항목명';
COMMENT ON COLUMN MLAY_TAX.VAL         IS '원본 표현 (예: X(10), 9(13))';
COMMENT ON COLUMN MLAY_TAX.FIELD_TYPE  IS '필드 타입 (x: 문자, 9: 숫자)';
COMMENT ON COLUMN MLAY_TAX.FIELD_LEN   IS '필드 길이 (바이트)';
COMMENT ON COLUMN MLAY_TAX.HWP_CUM     IS 'HWP 문서상 누적 바이트 (계산누적과 다르면 오타 의심)';
COMMENT ON COLUMN MLAY_TAX.SECT        IS '섹션 구분 (HEAD, BODY_1, BODY_2, FOOT)';

-- Java 레이아웃 (Java 소스 파싱 결과)
CREATE TABLE MLAY_JAVA (
  YEAR        NUMBER(4)       NOT NULL,
  USER_ID     NUMBER          NOT NULL,
  SEQ         NUMBER          NOT NULL,
  RECORD_TYPE VARCHAR2(1)     NOT NULL,
  JAVA_CODE   VARCHAR2(1000),
  ITEM        VARCHAR2(200),
  FIELD_TYPE  VARCHAR2(1),
  FIELD_LEN   NUMBER,
  CODE        VARCHAR2(10),
  LINE_NO     NUMBER          NOT NULL,
  SECT        VARCHAR2(10),
  BODY_ITER   NUMBER,
  CONSTRAINT PK_MLAY_JAVA PRIMARY KEY (YEAR, USER_ID, SEQ),
  CONSTRAINT FK_MLAY_JAVA  FOREIGN KEY (YEAR, USER_ID) REFERENCES MLAY_JAVA_FILE (YEAR, USER_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  MLAY_JAVA            IS 'Java 소스 파싱 결과 (전산매체 생성 Java 파일)';
COMMENT ON COLUMN MLAY_JAVA.YEAR       IS '귀속연도';
COMMENT ON COLUMN MLAY_JAVA.USER_ID    IS '업로드한 사용자';
COMMENT ON COLUMN MLAY_JAVA.SEQ         IS '파싱 순서 (1-based)';
COMMENT ON COLUMN MLAY_JAVA.RECORD_TYPE IS '레코드 타입 (A~K)';
COMMENT ON COLUMN MLAY_JAVA.JAVA_CODE   IS 'makeStr(...) 원본 코드';
COMMENT ON COLUMN MLAY_JAVA.ITEM        IS '항목명 주석';
COMMENT ON COLUMN MLAY_JAVA.FIELD_TYPE  IS '필드 타입 (x: 문자, 9: 숫자)';
COMMENT ON COLUMN MLAY_JAVA.FIELD_LEN   IS '필드 길이 (바이트)';
COMMENT ON COLUMN MLAY_JAVA.CODE        IS '항목코드 주석 (예: A1, C64ⓐ)';
COMMENT ON COLUMN MLAY_JAVA.LINE_NO     IS 'Java 파일 실제 라인 번호 (사용자 삽입 I행은 0)';
COMMENT ON COLUMN MLAY_JAVA.SECT        IS '섹션 구분 (HEAD, BODY_N, FOOT)';
COMMENT ON COLUMN MLAY_JAVA.BODY_ITER   IS 'BODY 반복 회차 (BODY 필드만)';

-- ============================================================
-- 섹션 설정
-- ============================================================

-- 섹션 설정 (귀속연도+사용자+레코드+대상 기준, 재업로드해도 보존)
CREATE TABLE MLAY_SECT_CONFIG (
  YEAR         NUMBER(4)       NOT NULL,
  USER_ID      NUMBER          NOT NULL,
  RECORD_TYPE  VARCHAR2(1)     NOT NULL,
  TARGET       VARCHAR2(4)     NOT NULL,
  SECT_MODE    VARCHAR2(5)     NOT NULL,
  BODY_START   NUMBER          DEFAULT 1,
  BODY_END     NUMBER          DEFAULT 1,
  REPEAT_COUNT NUMBER          DEFAULT 1,
  CONSTRAINT PK_MLAY_SECT_CFG  PRIMARY KEY (YEAR, USER_ID, RECORD_TYPE, TARGET),
  CONSTRAINT CK_MLAY_SECT_TGT  CHECK (TARGET IN ('TAX', 'JAVA')),
  CONSTRAINT CK_MLAY_SECT_MODE CHECK (SECT_MODE IN ('body', 'hbf'))
);

COMMENT ON TABLE  MLAY_SECT_CONFIG                IS '레코드별 섹션 구조 설정 (재업로드해도 보존)';
COMMENT ON COLUMN MLAY_SECT_CONFIG.YEAR           IS '귀속연도';
COMMENT ON COLUMN MLAY_SECT_CONFIG.USER_ID        IS '업로드한 사용자';
COMMENT ON COLUMN MLAY_SECT_CONFIG.RECORD_TYPE    IS '레코드 타입 (A~K)';
COMMENT ON COLUMN MLAY_SECT_CONFIG.TARGET         IS '적용 대상 (TAX: 국세청 HWP, JAVA: Java 소스)';
COMMENT ON COLUMN MLAY_SECT_CONFIG.SECT_MODE      IS '섹션 구조 (body: 전체 BODY, hbf: HEAD/BODY/FOOT)';
COMMENT ON COLUMN MLAY_SECT_CONFIG.BODY_START     IS 'BODY 시작 행 번호 (hbf 모드)';
COMMENT ON COLUMN MLAY_SECT_CONFIG.BODY_END       IS 'BODY 끝 행 번호 (hbf 모드)';
COMMENT ON COLUMN MLAY_SECT_CONFIG.REPEAT_COUNT   IS 'BODY 반복(분할) 횟수';

-- ============================================================
-- HWP 파싱 로그
-- ============================================================

-- HWP 파싱 시 원본→정제 변환 이력 (재업로드 시 초기화)
CREATE TABLE MLAY_HWP_PARSE_LOG (
  YEAR        NUMBER(4)       NOT NULL,
  USER_ID     NUMBER          NOT NULL,
  LOG_SEQ     NUMBER          NOT NULL,
  RECORD_TYPE VARCHAR2(1),
  CODE        VARCHAR2(20),
  ORIG_TEXT   VARCHAR2(2000),
  CLEAN_TEXT  VARCHAR2(2000),
  CONSTRAINT PK_MLAY_HWP_PARSE_LOG PRIMARY KEY (YEAR, USER_ID, LOG_SEQ)
);

COMMENT ON TABLE  MLAY_HWP_PARSE_LOG            IS 'HWP 파싱 시 원본→정제 변환 이력 (재업로드 시 초기화)';
COMMENT ON COLUMN MLAY_HWP_PARSE_LOG.YEAR       IS '귀속연도';
COMMENT ON COLUMN MLAY_HWP_PARSE_LOG.USER_ID    IS '업로드한 사용자';
COMMENT ON COLUMN MLAY_HWP_PARSE_LOG.LOG_SEQ    IS '로그 순서 (1-based)';
COMMENT ON COLUMN MLAY_HWP_PARSE_LOG.RECORD_TYPE IS '레코드 타입 (A~K)';
COMMENT ON COLUMN MLAY_HWP_PARSE_LOG.CODE       IS '항목코드';
COMMENT ON COLUMN MLAY_HWP_PARSE_LOG.ORIG_TEXT  IS '파싱 전 원본 텍스트';
COMMENT ON COLUMN MLAY_HWP_PARSE_LOG.CLEAN_TEXT IS '파싱 후 정제 텍스트';

-- ============================================================
-- 편집 레이어 (원본 테이블 불변, 편집만 별도 저장)
-- ============================================================

-- 국세청 항목코드 편집 (MLAY_TAX.CODE 원본 불변)
CREATE TABLE MLAY_TAX_CODE_EDIT (
  YEAR        NUMBER(4)       NOT NULL,
  USER_ID     NUMBER          NOT NULL,
  RECORD_TYPE VARCHAR2(1)     NOT NULL,
  ORG_CODE    VARCHAR2(10)    NOT NULL,
  CODE        VARCHAR2(10),
  EDIT_AT     DATE            DEFAULT SYSDATE,
  CONSTRAINT PK_MLAY_TAX_CODE_EDIT PRIMARY KEY (YEAR, USER_ID, RECORD_TYPE, ORG_CODE)
);

COMMENT ON TABLE  MLAY_TAX_CODE_EDIT             IS '국세청 항목코드 편집 (MLAY_TAX 원본 불변, 원본=수정값이면 자동 삭제)';
COMMENT ON COLUMN MLAY_TAX_CODE_EDIT.YEAR        IS '귀속연도';
COMMENT ON COLUMN MLAY_TAX_CODE_EDIT.USER_ID     IS '편집한 사용자';
COMMENT ON COLUMN MLAY_TAX_CODE_EDIT.RECORD_TYPE IS '레코드 타입 (A~K)';
COMMENT ON COLUMN MLAY_TAX_CODE_EDIT.ORG_CODE    IS '원본 항목코드 (PK 기준)';
COMMENT ON COLUMN MLAY_TAX_CODE_EDIT.CODE        IS '수정된 항목코드';
COMMENT ON COLUMN MLAY_TAX_CODE_EDIT.EDIT_AT     IS '최종 편집 일시';

-- 국세청 항목명 편집 (MLAY_TAX.ITEM 원본 불변)
CREATE TABLE MLAY_TAX_ITEM_EDIT (
  YEAR        NUMBER(4)       NOT NULL,
  USER_ID     NUMBER          NOT NULL,
  RECORD_TYPE VARCHAR2(1)     NOT NULL,
  ORG_ITEM    VARCHAR2(200)   NOT NULL,
  ITEM        VARCHAR2(200),
  EDIT_AT     DATE            DEFAULT SYSDATE,
  CONSTRAINT PK_MLAY_TAX_ITEM_EDIT PRIMARY KEY (YEAR, USER_ID, RECORD_TYPE, ORG_ITEM)
);

COMMENT ON TABLE  MLAY_TAX_ITEM_EDIT             IS '국세청 항목명 편집 (MLAY_TAX 원본 불변, 원본=수정값이면 자동 삭제)';
COMMENT ON COLUMN MLAY_TAX_ITEM_EDIT.YEAR        IS '귀속연도';
COMMENT ON COLUMN MLAY_TAX_ITEM_EDIT.USER_ID     IS '편집한 사용자';
COMMENT ON COLUMN MLAY_TAX_ITEM_EDIT.RECORD_TYPE IS '레코드 타입 (A~K)';
COMMENT ON COLUMN MLAY_TAX_ITEM_EDIT.ORG_ITEM    IS '원본 항목명 (PK 기준)';
COMMENT ON COLUMN MLAY_TAX_ITEM_EDIT.ITEM        IS '수정된 항목명';
COMMENT ON COLUMN MLAY_TAX_ITEM_EDIT.EDIT_AT     IS '최종 편집 일시';

-- Java makeStr 편집 (MLAY_JAVA.JAVA_CODE 원본 불변)
CREATE TABLE MLAY_JAVA_CODE_EDIT (
  YEAR      NUMBER(4)       NOT NULL,
  USER_ID   NUMBER          NOT NULL,
  SEQ       NUMBER          NOT NULL,
  JAVA_CODE VARCHAR2(1000),
  EDIT_AT   DATE            DEFAULT SYSDATE,
  CONSTRAINT PK_MLAY_JAVA_CODE_EDIT PRIMARY KEY (YEAR, USER_ID, SEQ)
);

COMMENT ON TABLE  MLAY_JAVA_CODE_EDIT          IS 'Java makeStr 편집 (MLAY_JAVA 원본 불변, M 명령 저장)';
COMMENT ON COLUMN MLAY_JAVA_CODE_EDIT.YEAR     IS '귀속연도';
COMMENT ON COLUMN MLAY_JAVA_CODE_EDIT.USER_ID  IS '편집한 사용자';
COMMENT ON COLUMN MLAY_JAVA_CODE_EDIT.SEQ      IS 'MLAY_JAVA.SEQ (원본 행만, LINE_NO=0 삽입행 제외)';
COMMENT ON COLUMN MLAY_JAVA_CODE_EDIT.JAVA_CODE IS '수정된 makeStr 표현식';
COMMENT ON COLUMN MLAY_JAVA_CODE_EDIT.EDIT_AT  IS '최종 편집 일시';

-- ============================================================
-- 비교검증 매핑 (현행)
-- ============================================================

-- 전산매체↔Java 1:1 매핑 및 D/I/O 행 관리
-- FK 없음 — HWP/Java 재업로드 시 앱에서 직접 DELETE 후 재생성
CREATE TABLE MLAY_TAX_JAVA_MAP (
  YEAR        NUMBER(4)       NOT NULL,
  USER_ID     NUMBER          NOT NULL,
  RECORD_TYPE VARCHAR2(1)     NOT NULL,
  SORT_ORDER  NUMBER          NOT NULL,
  TAX_SEQ     NUMBER,
  JAVA_SEQ    NUMBER,
  ROW_TYPE    VARCHAR2(1),
  CONSTRAINT PK_MLAY_TAX_JAVA_MAP  PRIMARY KEY (YEAR, USER_ID, RECORD_TYPE, SORT_ORDER),
  CONSTRAINT CK_MLAY_MAP_ROW_TYPE  CHECK (ROW_TYPE IN ('D', 'O'))
);

COMMENT ON TABLE  MLAY_TAX_JAVA_MAP             IS '전산매체↔Java 1:1 매핑 (FK 없음, 재업로드 시 앱에서 리셋)';
COMMENT ON COLUMN MLAY_TAX_JAVA_MAP.YEAR        IS '귀속연도';
COMMENT ON COLUMN MLAY_TAX_JAVA_MAP.USER_ID     IS '사용자';
COMMENT ON COLUMN MLAY_TAX_JAVA_MAP.RECORD_TYPE IS '레코드 타입 (A~K)';
COMMENT ON COLUMN MLAY_TAX_JAVA_MAP.SORT_ORDER  IS '화면 표시 순서 (1-based)';
COMMENT ON COLUMN MLAY_TAX_JAVA_MAP.TAX_SEQ     IS '매치된 MLAY_TAX.SEQ (overflow 행은 0)';
COMMENT ON COLUMN MLAY_TAX_JAVA_MAP.JAVA_SEQ    IS '매치된 MLAY_JAVA.SEQ (D 행은 NULL, I 삽입 후 MLAY_JAVA.SEQ 참조)';
COMMENT ON COLUMN MLAY_TAX_JAVA_MAP.ROW_TYPE    IS '행 유형 (D: Java 삭제, O: overflow, NULL: 정상 매치)';

-- ============================================================
-- 비교검증 매핑 (구버전, 레거시)
-- 현재는 MLAY_TAX_JAVA_MAP으로 대체됨.
-- 재업로드 시 앱이 이 테이블도 DELETE하므로 테이블은 유지.
-- ============================================================
CREATE TABLE MLAY_COMPARE (
  YEAR        NUMBER(4)       NOT NULL,
  USER_ID     NUMBER          NOT NULL,
  RECORD_TYPE VARCHAR2(1)     NOT NULL,
  SEQ         NUMBER          NOT NULL,
  TAX_SEQ     NUMBER,
  JAVA_SEQ    NUMBER,
  CMD         VARCHAR2(1),
  EDITED_RAW  VARCHAR2(1000),
  CONSTRAINT PK_MLAY_COMPARE PRIMARY KEY (YEAR, USER_ID, RECORD_TYPE, SEQ),
  CONSTRAINT CK_MLAY_CMP_CMD CHECK (CMD IN ('D', 'I', 'M'))
);

COMMENT ON TABLE MLAY_COMPARE IS '[레거시] 구버전 비교검증 매핑 — MLAY_TAX_JAVA_MAP으로 대체됨, 재업로드 시 앱에서 DELETE';

-- ============================================================
-- HWP 항목 주목 메모
-- ============================================================

-- HWP 업로드 화면에서 주목 항목에 메모, 비교검증 화면에서 스티커로 확인
-- PK: (YEAR, USER_ID, RECORD_TYPE, CODE) — CODE 기반, HWP 재업로드 시 노트 유지
CREATE TABLE MLAY_ITEM_NOTE (
  YEAR        NUMBER(4)      NOT NULL,
  USER_ID     NUMBER         NOT NULL,
  RECORD_TYPE VARCHAR2(1)    NOT NULL,
  CODE        VARCHAR2(20)   NOT NULL,
  MEMO        VARCHAR2(2000),
  IS_DONE     NUMBER(1)      DEFAULT 0  NOT NULL,
  COLOR       VARCHAR2(10)   DEFAULT 'yellow' NOT NULL,
  CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MLAY_ITEM_NOTE  PRIMARY KEY (YEAR, USER_ID, RECORD_TYPE, CODE),
  CONSTRAINT CK_ITEM_NOTE_DONE  CHECK (IS_DONE IN (0, 1)),
  CONSTRAINT CK_ITEM_NOTE_COLOR CHECK (COLOR IN ('yellow','red','blue','green'))
);

COMMENT ON TABLE  MLAY_ITEM_NOTE             IS 'HWP 항목 주목 메모 (HWP 재업로드 시 유지, CODE 수정 시 고아 허용)';
COMMENT ON COLUMN MLAY_ITEM_NOTE.YEAR        IS '귀속연도';
COMMENT ON COLUMN MLAY_ITEM_NOTE.USER_ID     IS '작성자 ID';
COMMENT ON COLUMN MLAY_ITEM_NOTE.RECORD_TYPE IS '레코드 구분 (A~K)';
COMMENT ON COLUMN MLAY_ITEM_NOTE.CODE        IS '항목 코드 (예: E31)';
COMMENT ON COLUMN MLAY_ITEM_NOTE.MEMO        IS '주목 사유 / 메모';
COMMENT ON COLUMN MLAY_ITEM_NOTE.IS_DONE     IS '처리완료 여부 (0:미완료, 1:완료)';
COMMENT ON COLUMN MLAY_ITEM_NOTE.COLOR       IS '스티커 색상 (yellow/red/blue/green)';
COMMENT ON COLUMN MLAY_ITEM_NOTE.CREATED_AT  IS '작성 일시';
COMMENT ON COLUMN MLAY_ITEM_NOTE.UPDATED_AT  IS '수정 일시';

-- ============================================================
-- 인덱스
-- ============================================================
CREATE INDEX IX_MLAY_TAX_REC      ON MLAY_TAX          (YEAR, USER_ID, RECORD_TYPE);
CREATE INDEX IX_MLAY_JAVA_REC     ON MLAY_JAVA          (YEAR, USER_ID, RECORD_TYPE);
CREATE INDEX IX_MLAY_MAP_REC      ON MLAY_TAX_JAVA_MAP  (YEAR, USER_ID, RECORD_TYPE);
CREATE INDEX IX_MLAY_PARSE_LOG    ON MLAY_HWP_PARSE_LOG (YEAR, USER_ID);
