-- ============================================================
-- 과제관리 테이블 (YTTS DB)
-- ============================================================

BEGIN EXECUTE IMMEDIATE 'DROP TABLE TASK_FILE  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TASK_LOG   CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TASK_ITEM  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TASK_GROUP CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE TASK_FILE_SEQ';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE TASK_LOG_SEQ';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE TASK_ITEM_SEQ';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE TASK_GROUP_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ── 시퀀스 ──────────────────────────────────────────────────
CREATE SEQUENCE TASK_GROUP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE TASK_ITEM_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE TASK_LOG_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE TASK_FILE_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- ── 과제구분 ────────────────────────────────────────────────
CREATE TABLE TASK_GROUP (
  GROUP_ID   NUMBER        NOT NULL,
  GROUP_NAME VARCHAR2(200) NOT NULL,
  YEAR_CD    VARCHAR2(4),
  NOTES      CLOB,
  SORT_ORDER NUMBER        DEFAULT 0,
  CREATED_AT DATE          DEFAULT SYSDATE,
  CREATED_BY VARCHAR2(100),
  CONSTRAINT PK_TASK_GROUP PRIMARY KEY (GROUP_ID)
);
/

-- ── 과제항목 ────────────────────────────────────────────────
CREATE TABLE TASK_ITEM (
  ITEM_ID    NUMBER        NOT NULL,
  GROUP_ID   NUMBER        NOT NULL,
  SEQ_NO     NUMBER        DEFAULT 0,
  CATEGORY   VARCHAR2(100),
  TITLE      VARCHAR2(500) NOT NULL,
  IMPL_PLAN  CLOB,
  STATUS     VARCHAR2(20)  DEFAULT '미정',
  PRIORITY   VARCHAR2(10)  DEFAULT '보통',
  ASSIGNEE   VARCHAR2(100),
  START_DT   DATE,
  END_DT     DATE,
  REMARKS    CLOB,
  CREATED_AT DATE          DEFAULT SYSDATE,
  CREATED_BY VARCHAR2(100),
  UPDATED_AT DATE          DEFAULT SYSDATE,
  UPDATED_BY VARCHAR2(100),
  CONSTRAINT PK_TASK_ITEM  PRIMARY KEY (ITEM_ID),
  CONSTRAINT FK_TASK_ITEM_GROUP FOREIGN KEY (GROUP_ID)
    REFERENCES TASK_GROUP(GROUP_ID) ON DELETE CASCADE
);
/

-- ── 진척로그 ────────────────────────────────────────────────
CREATE TABLE TASK_LOG (
  LOG_ID     NUMBER NOT NULL,
  ITEM_ID    NUMBER NOT NULL,
  CONTENT    CLOB   NOT NULL,
  LOGGED_BY  VARCHAR2(100),
  LOGGED_AT  DATE   DEFAULT SYSDATE,
  CONSTRAINT PK_TASK_LOG  PRIMARY KEY (LOG_ID),
  CONSTRAINT FK_TASK_LOG_ITEM FOREIGN KEY (ITEM_ID)
    REFERENCES TASK_ITEM(ITEM_ID) ON DELETE CASCADE
);
/

-- ── 첨부파일 ────────────────────────────────────────────────
CREATE TABLE TASK_FILE (
  FILE_ID     NUMBER        NOT NULL,
  ITEM_ID     NUMBER        NOT NULL,
  LOG_ID      NUMBER,
  FILE_NAME   VARCHAR2(500) NOT NULL,
  FILE_PATH   VARCHAR2(1000) NOT NULL,
  FILE_SIZE   NUMBER,
  MIME_TYPE   VARCHAR2(100),
  UPLOADED_BY VARCHAR2(100),
  UPLOADED_AT DATE          DEFAULT SYSDATE,
  CONSTRAINT PK_TASK_FILE      PRIMARY KEY (FILE_ID),
  CONSTRAINT FK_TASK_FILE_ITEM FOREIGN KEY (ITEM_ID)
    REFERENCES TASK_ITEM(ITEM_ID) ON DELETE CASCADE,
  CONSTRAINT FK_TASK_FILE_LOG  FOREIGN KEY (LOG_ID)
    REFERENCES TASK_LOG(LOG_ID)  ON DELETE SET NULL
);
/
