-- ── MLAY_ITEM_NOTE : HWP 항목 주목 메모 ─────────────────────────
-- HWP 업로드 화면에서 이번 작업 시 주목할 항목에 메모를 달고,
-- 전산매체 비교검증 화면에서 스티커 형태로 확인한다.
-- PK: (YEAR, USER_ID, RECORD_TYPE, CODE)
-- ※ CODE 기반 — HWP 재업로드 시 노트 유지, CODE 수정 시 고아 발생 허용

CREATE TABLE MLAY_ITEM_NOTE (
  YEAR          NUMBER(4)      NOT NULL,
  USER_ID       NUMBER         NOT NULL,
  RECORD_TYPE   VARCHAR2(1)    NOT NULL,
  CODE          VARCHAR2(20)   NOT NULL,
  MEMO          VARCHAR2(2000),
  IS_DONE       NUMBER(1)      DEFAULT 0  NOT NULL,
  COLOR         VARCHAR2(10)   DEFAULT 'yellow' NOT NULL,
  CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MLAY_ITEM_NOTE PRIMARY KEY (YEAR, USER_ID, RECORD_TYPE, CODE),
  CONSTRAINT CK_ITEM_NOTE_DONE  CHECK (IS_DONE IN (0, 1)),
  CONSTRAINT CK_ITEM_NOTE_COLOR CHECK (COLOR IN ('yellow','red','blue','green'))
);

COMMENT ON TABLE  MLAY_ITEM_NOTE            IS 'HWP 항목 주목 메모';
COMMENT ON COLUMN MLAY_ITEM_NOTE.YEAR       IS '귀속연도';
COMMENT ON COLUMN MLAY_ITEM_NOTE.USER_ID    IS '작성자 ID';
COMMENT ON COLUMN MLAY_ITEM_NOTE.RECORD_TYPE IS '레코드 구분 (A~K)';
COMMENT ON COLUMN MLAY_ITEM_NOTE.CODE       IS '항목 코드 (예: E31)';
COMMENT ON COLUMN MLAY_ITEM_NOTE.MEMO       IS '주목 사유 / 메모';
COMMENT ON COLUMN MLAY_ITEM_NOTE.IS_DONE    IS '처리완료 여부 (0:미완료, 1:완료)';
COMMENT ON COLUMN MLAY_ITEM_NOTE.COLOR      IS '스티커 색상 (yellow/red/blue/green)';
COMMENT ON COLUMN MLAY_ITEM_NOTE.CREATED_AT IS '작성 일시';
COMMENT ON COLUMN MLAY_ITEM_NOTE.UPDATED_AT IS '수정 일시';
